### ISSUE TITLE
python client does not build

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1090]
on both the master cc0cfe19a and on stable-5.0.x the build of the python bindings give me:
```
[100%] Built target XrdClProxyPlugin-5
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libXrdPosix.so: undefined reference to `vtable for XrdOucCacheDram'
collect2: error: ld returned 1 exit status
make[2]: *** [src/api_test/CMakeFiles/xrd_api_test.dir/build.make:88: src/api_test/xrd_api_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:1319: src/api_test/CMakeFiles/xrd_api_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target xrdcp
[100%] Built target xrdfs
[100%] Built target python_target
make: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
File "./setup.py", line 136, in <module>
'bdist_wheel': CustomWheelGen
File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "./setup.py", line 96, in run
raise Exception( 'Install step failed!' )
Exception: Install step failed!
```

**Comment by simonmichal** [comment]
@adriansev : with your PR merged, I suppose also this one should go away, could you please check?

**Comment by adriansev** [comment]
yes, actually this was another problem, there is no upstream cmake 3.x on centos 7, there is only a cmake3 package in epel. so install.sh fails unless cmake command is replaced by cmake3. this can be closed
