### ISSUE TITLE
XrdAccSciTokens issues

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1313]
Using the following `/etc/xrootd/scitokens.cfg`

```
[Global]
audience = https://wlcg.cern.ch/jwt/v1/any

[Issuer OSG-Connect]
issuer = https://wlcg.cloud.cnaf.infn.it/
base_path = /
map_subject = False
default_user = dteam001
```

And a properly generated token to do a simple curl PUT request, we get the following error:
```
scitokens_GenerateAcls: Failed to deserialize SciToken: SSL peer certificate or SSH remote key was not OK
```

Sometimes, the thread handling the request gets blocked there (ignore the last few frames as these are EOS specific).
```
Thread 8 "xrootd" received signal SIGINT, Interrupt.
0x00007f282ab05c3d in poll () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f282ab05c3d in poll () from /lib64/libc.so.6
#1  0x00007f282178e8c9 in Curl_poll () from /lib64/libcurl.so.4
#2  0x00007f28217877ad in curl_multi_wait () from /lib64/libcurl.so.4
#3  0x00007f282178082f in curl_easy_perform () from /lib64/libcurl.so.4
#4  0x00007f27ddde99ae in (anonymous namespace)::SimpleCurlGet::perform(std::string const&) () from /lib64/libSciTokens.so.0
#5  0x00007f27dddebebc in scitokens::Validator::get_public_keys_from_web(std::string const&, picojson::value&, long&, long&) () from /lib64/libSciTokens.so.0
#6  0x00007f27dddecbde in scitokens::Validator::get_public_key_pem(std::string const&, std::string const&, std::string&, std::string&) () from /lib64/libSciTokens.so.0
#7  0x00007f27ddde77db in scitokens::Validator::verify(jwt::decoded_jwt const&) () from /lib64/libSciTokens.so.0
#8  0x00007f27dddee81d in scitokens::SciToken::deserialize(std::string const&, std::vector<std::string, std::allocator<std::string> >) () from /lib64/libSciTokens.so.0
#9  0x00007f27dddda7b4 in scitoken_deserialize () from /lib64/libSciTokens.so.0
#10 0x00007f27df5f025c in XrdAccSciTokens::GenerateAcls (this=this@entry=0x7f279f9da980, 
    authz="Bearer%20eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJ3bGNnLnZlciI6IjEuMCIsInN1YiI6ImZhZGVkNDljLWUxYmMtNDIwOC05NjM0LTY4MmIyYjhkMTZlNSIsImF1ZCI6Imh0dHBzOlwvXC93bGNnLmNlcm4uY2hcL2p3dFwvdjFcL2FueSIsIm5iZiI6"..., cache_expiry=@0x7f28295fc240: 4, 
    rules=std::vector of length 0, capacity 0, username="", issuer="") at /usr/src/debug/eos-scitokens-1.2.0/src/scitokens.cpp:356
#11 0x00007f27df5f850b in XrdAccSciTokens::Access (this=0x7f279f9da980, Entity=0x7f27e794a040, path=0x7f27d8069558 "/eos/pps/users/esindril/yfile1.dat", oper=AOP_Create, env=0x7f27e7882380) at /usr/src/debug/eos-scitokens-1.2.0/src/scitokens.cpp:267
#12 0x00007f27e35f89c0 in Macaroons::Authz::Access (this=0x7f2716d56560, Entity=0x7f27e794a040, path=0x7f27d8069558 "/eos/pps/users/esindril/yfile1.dat", oper=AOP_Create, env=0x7f27e7882380) at /usr/src/debug/xrootd-4.12.5/src/XrdMacaroons/XrdMacaroonsAuthz.cc:166
#13 0x00007f27e4df4b99 in EosMgmHttpHandler::ProcessReq (this=0x7f282a3a6a00, req=...) at /root/rpmbuild/BUILD/eos-4.8.24-1/mgm/http/xrdhttp/EosMgmHttpHandler.hh:64
#14 0x00007f2827cd601c in XrdHttpReq::ProcessHTTPReq (this=this@entry=0x7f26ec806aa0) at /usr/src/debug/xrootd-4.12.5/src/XrdHttp/XrdHttpReq.cc:987
#15 0x00007f2827cce55d in XrdHttpProtocol::Process (this=0x7f26ec806980, lp=<optimized out>) at /usr/src/debug/xrootd-4.12.5/src/XrdHttp/XrdHttpProtocol.cc:843
#16 0x00007f282bc91b59 in XrdLink::DoIt (this=0x7f278a4892b8) at /usr/src/debug/xrootd-4.12.5/src/Xrd/XrdLink.cc:441
#17 0x00007f282bc94eef in XrdScheduler::Run (this=0x610e78 <XrdMain::Config+440>) at /usr/src/debug/xrootd-4.12.5/src/Xrd/XrdScheduler.cc:357
#18 0x00007f282bc95039 in XrdStartWorking (carg=<optimized out>) at /usr/src/debug/xrootd-4.12.5/src/Xrd/XrdScheduler.cc:87
#19 0x00007f282bc5aaa7 in XrdSysThread_Xeq (myargs=0x7f282a020560) at /usr/src/debug/xrootd-4.12.5/src/XrdSys/XrdSysPthread.cc:86
#20 0x00007f282b80eea5 in start_thread () from /lib64/libpthread.so.0
#21 0x00007f282ab108dd in clone () from /lib64/libc.so.6
(gdb) f 4
```

Is this an issue with the IAM? Any hints on what to do in this case? @bbockelm

**Comment by esindril** [comment]
Following the instructions below and installing the required rpm fixed this issue.

> > Dear all,
> > 
> > a new certificate for the WLCG VOMS VO server has been rolled out.
> > 
> > Due to INFN changing certificate authority, the LSC file has changed,
> > and needs to be updated on all nodes that supports the WLCG VO.
> > 
> > The updated LSC file can be downloaded at the following URL:
> > 
> > https://wlcg-authz-wg.github.io/wlcg-authz-docs/#wlcg-vo-voms-configuration
> > 
> > There's also an RPM package providing the configuration that can
> > be installed as follows:
> > 
> > yum localinstall https://repo.cloud.cnaf.infn.it/repository/infn-vos/centos7/infn-vo-wlcg-1.0.0-0.el7.noarch.rpm
> > 
> > Cheers,
> > Andrea
