### ISSUE TITLE
XrdTpc PUSH calls Write on the local file opened for reading

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1373]
This was introduced in #1316 and now `TPC::State::Flush/Write` is called for both PUSH and PULL operations. This leads to  an error (at least in EOS) since in the PUSH mode the file is opened in read only mode and the write operation will fail.

Doing the following in the `TPC::State::Flush` method should be enough to avoid this issue:

```
int State::Flush() {
    if (m_push) {
      return 0;
    }

    int retval = m_stream->Write(m_start_offset + m_offset, 0, 0, true);
    ....
```

Below is a stacktrace to better understand where this happens:
```
(gdb) bt
#0  XrdMgmOfsFile::write (this=0x7f6c5e657000, offset=0, buff=0x0, blen=0) at ../mgm/XrdMgmOfsFile.cc:3058
#1  0x00007f6bef31517a in TPC::Stream::Write (this=0x7f6be664dd30, offset=0, buf=buf@entry=0x0, size=size@entry=0, force=force@entry=true) at /usr/src/debug/xrootd/xrootd/src/XrdTpc/XrdTpcStream.cc:80
#2  0x00007f6bef312984 in TPC::State::Flush (this=this@entry=0x7f6be664dd80) at /usr/src/debug/xrootd/xrootd/src/XrdTpc/XrdTpcState.cc:203
#3  0x00007f6bef31ddd1 in TPC::TPCHandler::RunCurlWithUpdates (this=this@entry=0x7f6c54d94e00, curl=curl@entry=0x7f6c5e630d40, req=..., state=..., rec=...)
    at /usr/src/debug/xrootd/xrootd/src/XrdTpc/XrdTpcTPC.cc:491
#4  0x00007f6bef320cff in TPC::TPCHandler::ProcessPushReq (this=this@entry=0x7f6c54d94e00, resource=": https://esdss000.cern.ch:9000/eos/dev/replica/zero1.dat", req=...)
    at /usr/src/debug/xrootd/xrootd/src/XrdTpc/XrdTpcTPC.cc:648
#5  0x00007f6bef322f4c in TPC::TPCHandler::ProcessReq (this=0x7f6c54d94e00, req=...) at /usr/src/debug/xrootd/xrootd/src/XrdTpc/XrdTpcTPC.cc:132
#6  0x00007f6ca6c1501c in XrdHttpReq::ProcessHTTPReq (this=this@entry=0x7f6c62ffc4a0) at /usr/src/debug/xrootd/xrootd/src/XrdHttp/XrdHttpReq.cc:987
#7  0x00007f6ca6c0d55d in XrdHttpProtocol::Process (this=0x7f6c62ffc380, lp=<optimized out>) at /usr/src/debug/xrootd/xrootd/src/XrdHttp/XrdHttpProtocol.cc:843
#8  0x00007f6cab677e49 in XrdLink::DoIt (this=0x7f6c6263b028) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdLink.cc:441
#9  0x00007f6cab67b1df in XrdScheduler::Run (this=0x610e58 <XrdMain::Config+440>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:357
#10 0x00007f6cab67b329 in XrdStartWorking (carg=<optimized out>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:87
#11 0x00007f6cab640be7 in XrdSysThread_Xeq (myargs=0x7f6c5f1c6200) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.cc:86
#12 0x00007f6cab1f4ea5 in start_thread (arg=0x7f6be6650700) at pthread_create.c:307
#13 0x00007f6caa4f68dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

I guess this is of interest for @bbockelm. Thanks!

**Comment by bbockelm** [comment]
Thanks for the report @esindril.  I'm trying to clear out some xrootd time in my schedule early this week and I think this item is my top priority.

**Comment by abh3** [comment]
@bbockelm Please look at ticket 1384 as there are even more issues with XrdTpc some of which I outline but those are the ones that cause a crash frequently. I haven't yet determined what is causing the infrequent crashes.
