### ISSUE TITLE
Installation can fail if the python3.x alias is not in PATH

### ISSUE THREAD

**Issue by lmoureaux** [xrootd/xrootd#1427]
For instance, installing in a virtualenv with only `python3` in the `bin` folder and `python3.8` not in `PATH` fails with the following output:
```
[...]
    -- Installing: /storage_mnt/storage/user/lmoureau/nanoaod/venv/lib/python3.8/site-packages/pyxrootd/include/xrootd/private/XrdCl/XrdClZipOperations.hh
    ./install.sh: line 37: python3.8: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hzwjyn3t/xrootd/setup.py", line 141, in <module>
        setup(
      File "/cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc10-opt/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc10-opt/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc10-opt/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc10-opt/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-hzwjyn3t/xrootd/setup.py", line 118, in run
        raise Exception( 'Install step failed!' )
    Exception: Install step failed!
    ----------------------------------------
```

Creating a symlink `venv/bin/python3.8` pointing to `venv/bin/python3` worked around the problem.

This appears to be caused by heuristics used to determine the `python` command around this line:

https://github.com/xrootd/xrootd/blob/222014a65ed28f4ef26bd501e18516a06d3386b0/packaging/wheel/setup.py#L113

Passing the absolute path of the interpreter ([`sys.executable`](https://docs.python.org/3.8/library/sys.html#sys.executable))  would probably be more robust.

**Comment by simonmichal** [comment]
@lmoureaux : thanks for reporting this problem, well the `py_version_short` goes to 
https://github.com/xrootd/xrootd/blob/cbd73ee8ea77a89e8eccfc0e412ee1c5128ea47f/cmake/XRootDFindLibs.cmake#L127-L128
as `XRD_PYTHON_REQ_VERSION` so `sys.executable` won't do, but let me play a bit with it, maybe this could be a hint.

**Comment by simonmichal** [comment]
@lmoureaux : sorry now I see your point, the value is also used in here:
https://github.com/xrootd/xrootd/blob/cbd73ee8ea77a89e8eccfc0e412ee1c5128ea47f/packaging/wheel/install.sh#L41

yes this we can fix with `sys.executable`

**Comment by lmoureaux** [comment]
Yes that was the line mentioned in the above stack trace.

**Comment by lmoureaux** [comment]
Thanks for the fix! :heart:

**Comment by simonmichal** [comment]
My pleasure :-)
