### ISSUE TITLE
Python3 bindings segfault on PyXRootD::FileSystem::Prepare()

### ISSUE THREAD

**Issue by Einscrew** [xrootd/xrootd#1810]
I faced this problem when porting python2 code we use on EOS to issue transferes from and into tape. I was also able to reproduce it on a forked repo https://github.com/Einscrew/xrootd/commit/b125c81ce2f99bd3e334075a25b04af16180aae8
```
$ gdb --args python3 -c 'from XRootD import client; from XRootD.client.flags import PrepareFlags; fs=client.FileSystem("root://localhost:1094"); print(fs); fs.prepare(["/eos/cms/opstest/mbatalha/ola"], PrepareFlags.STAGE)'
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python3.6...Reading symbols from /usr/bin/python3.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Missing separate debuginfos, use: debuginfo-install python3-3.6.8-18.el7.x86_64
(gdb) r
Starting program: /usr/bin/python3 -c from\ XRootD\ import\ client\;\ from\ XRootD.client.flags\ import\ PrepareFlags\;\ fs=client.FileSystem\(\"root://localhost:1094\"\)\;\ print\(fs\)\;\ fs.prepare\(\[\"/eos/cms/opstest/mbatalha/ola\"\],\ PrepareFlags.STAGE\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
<XRootD.client.filesystem.FileSystem object at 0x7ffff7e77f98>

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff0469364 in PyXRootD::FileSystem::Prepare (self=0x7ffff7e4abf0, args=0x7fffeb274f98, kwds=0x0) at /usr/src/debug/xrootd/xrootd/bindings/python/src/PyXRootDFileSystem.cc:622
622	    if ( !PyList_Check( pyfiles ) ) {
(gdb) bt
#0  0x00007ffff0469364 in PyXRootD::FileSystem::Prepare (self=0x7ffff7e4abf0, args=0x7fffeb274f98, kwds=0x0) at /usr/src/debug/xrootd/xrootd/bindings/python/src/PyXRootDFileSystem.cc:622
#1  0x00007ffff79997e7 in _PyCFunction_FastCallDict () from /lib64/libpython3.6m.so.1.0
#2  0x00007ffff7a0514f in call_function () from /lib64/libpython3.6m.so.1.0
#3  0x00007ffff79f9a17 in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
#4  0x00007ffff7a04317 in _PyEval_EvalCodeWithName () from /lib64/libpython3.6m.so.1.0
#5  0x00007ffff7a04fea in fast_function () from /lib64/libpython3.6m.so.1.0
#6  0x00007ffff7a05273 in call_function () from /lib64/libpython3.6m.so.1.0
#7  0x00007ffff79f9a17 in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
#8  0x00007ffff7a055ed in PyEval_EvalCodeEx () from /lib64/libpython3.6m.so.1.0
#9  0x00007ffff7a0610b in PyEval_EvalCode () from /lib64/libpython3.6m.so.1.0
#10 0x00007ffff7a8e53e in run_mod () from /lib64/libpython3.6m.so.1.0
#11 0x00007ffff7a8ebc2 in PyRun_StringFlags () from /lib64/libpython3.6m.so.1.0
#12 0x00007ffff793a8a9 in PyRun_SimpleStringFlags () from /lib64/libpython3.6m.so.1.0
#13 0x00007ffff7a948aa in Py_Main () from /lib64/libpython3.6m.so.1.0
#14 0x0000000000400ab9 in main ()
(gdb) info locals
kwlist = {0x7ffff0471d93 "files", 0x7ffff04717e7 "flags", 0x7ffff0471d99 "priority", 0x7ffff04714c7 "timeout", 0x7ffff0471759 "callback", 0x0}
flags = XrdCl::PrepareFlags::Stage
priority = 0 '\000'
timeout = 0
pyfiles = 0x7fff00000000
callback = 0x0
pyresponse = 0x0
pystatus = 0x0
status = {<XrdCl::Status> = {status = 0, code = 0, errNo = 0}, pMessage = ""}
files = std::vector of length -551453457066920787, capacity 16995866 = {<error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, 
...
file = <optimized out>
pyfile = <optimized out>
o = <optimized out>
 ```

**Comment by smithdh** [comment]
I've been doing some testing with Manuel, probably this is the fix:

```
diff --git a/bindings/python/src/PyXRootDFileSystem.cc b/bindings/python/src/PyXRootDFileSystem.cc
index d53fbd7..97abf83 100644
--- a/bindings/python/src/PyXRootDFileSystem.cc
+++ b/bindings/python/src/PyXRootDFileSystem.cc
@@ -615,7 +615,7 @@ namespace PyXRootD
     PyObject                  *pyresponse = NULL, *pystatus = NULL;
     XrdCl::XRootDStatus        status;
 
-    if ( !PyArg_ParseTupleAndKeywords( args, kwds, "OK|bHO:prepare",
+    if ( !PyArg_ParseTupleAndKeywords( args, kwds, "OH|bHO:prepare",
          (char**) kwlist, &pyfiles, &flags, &priority, &timeout, &callback ) )
       return NULL;
```

However still going over tests with him to confirm & see if anything is needed.

**Comment by simonmichal** [comment]
@smithdh & @Einscrew : my understanding is this is fixed, can we close this issue?

**Comment by smithdh** [comment]
Hi. This issue should be fixed with PR 1818. Would you like to comment or adjust that PR before merging?

**Comment by smithdh** [comment]
I'll close this issue. We can comment on the PR if needed.
