### ISSUE TITLE
libXrdCl: application crash under XrdCl::DefaultEnv::DefaultEnv()

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#1812]
We've seen 2 crashes by the same user, different machines. The top-level entry point is `eos` but  posting here as the backtrace seems to be pure `xrootd-client`:
```
:Core was generated by `eos quota /eos/project/c/compass-publicweb/www/w1/transparencies'.
:Program terminated with signal 11, Segmentation fault.
:#0  0x00007f781ad5b06a in ?? ()
:#0  0x00007f781ad5b06a in ?? ()
:#1  0x00007f781cef026a in operator-- (this=<synthetic pointer>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:2044
:#2  std::_Rb_tree<int, std::pair<int const, std::string>, std::_Select1st<std::pair<int const, std::string> >, std::less<int>, std::allocator<std::pair<int const, std::string> > >::_M_get_insert_unique_pos (this=this@entry=0x7f781d1b9860 <(anonymous namespace)::e2sMap>, __k=@0xe42630: 2) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:2063
:#3  0x00007f781cef033f in std::_Rb_tree<int, std::pair<int const, std::string>, std::_Select1st<std::pair<int const, std::string> >, std::less<int>, std::allocator<std::pair<int const, std::string> > >::_M_get_insert_hint_unique_pos (this=this@entry=0x7f781d1b9860 <(anonymous namespace)::e2sMap>, __position=..., __k=@0xe42630: 2) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:2146
:#4  0x00007f781cef03a8 in std::_Rb_tree<int, std::pair<int const, std::string>, std::_Select1st<std::pair<int const, std::string> >, std::less<int>, std::allocator<std::pair<int const, std::string> > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<int const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<int const, std::string> >, std::piecewise_construct_t const&, std::tuple<int const&>&&, std::tuple<>&&) (this=this@entry=0x7f781d1b9860 <(anonymous namespace)::e2sMap>, __pos=__pos@entry=..., __args#0=..., __args#1=__args#1@entry=<unknown type in /usr/lib/debug/opt/eos/xrootd/lib64/libXrdUtils.so.3.0.0.debug, CU 0x17751, DIE 0x1aab8>, __args#2=__args#2@entry=<unknown type in /usr/lib/debug/opt/eos/xrootd/lib64/libXrdUtils.so.3.0.0.debug, CU 0x17751, DIE 0x1aaca>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/new:169
:#5  0x00007f781ceeff8e in operator[] (__k=@0x7fff8b19046c: 2, this=0x7f781d1b9860 <(anonymous namespace)::e2sMap>) at /usr/src/debug/xrootd-5.5.1/src/XrdSys/XrdSysE2T.cc:107
:#6  XrdSysE2T(int) () at /usr/src/debug/xrootd-5.5.1/src/XrdSys/XrdSysE2T.cc:107
:#7  0x00007f781b14abb4 in XrdCl::Status::ToString() const () at /usr/src/debug/xrootd-5.5.1/src/XProtocol/XProtocol.hh:1400
:#8  0x00007f781b1445bc in XrdCl::DefaultEnv::DefaultEnv() () at /usr/src/debug/xrootd-5.5.1/src/XrdCl/XrdClDefaultEnv.cc:343
:#9  0x00007f781b145576 in XrdCl::DefaultEnv::Initialize() () at /usr/src/debug/xrootd-5.5.1/src/XrdCl/XrdClDefaultEnv.cc:691
:#10 0x00007f7817110450 in ?? ()
:#11 0x00007fff8b1918e8 in ?? ()
:#12 0x00007f781e16e9c3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
:#13 0x00007f781e16017a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
:#14 0x0000000000000003 in ?? ()
:#15 0x00007fff8b193013 in ?? ()
:#16 0x00007fff8b193017 in ?? ()
:#17 0x00007fff8b19301d in ?? ()
:#18 0x0000000000000000 in ?? ()
```
the error seems to be coming from the "Debug()"-Function trying to translate an error string (and add to the `e2sMap`):
```code
    340       st = Utils::ProcessConfig( userConfig, userConfigFile );
    341 
    342       if( !st.IsOK() )
    343         log->Debug( UtilityMsg, "Unable to process user config file: %s",
    344                     st.ToString().c_str() );
```
The user does not seem to have a `$HOME/.xrootd/client.conf` (which would match errno "2"=ENOENT) - but then pretty much nobody else does either..
```
 rpm -qf /opt/eos/xrootd/lib64/libXrdCl.so.3
(none):eos-xrootd-5.5.1-1.el7.cern.x86_64
```
(am trying to get more information from the user. Has `LD_LIBRARY_PATH` set but that does not seem to affect the actual libraries used here)

**Comment by abh3** [comment]
Weird, it would appear that memory was corrupted. What was the user doing each time?

**Comment by jmuf** [comment]
Meanwhile, our user has confirmed that they were running ".. accidentally in a weird environment [..]. The LD_LIBRARY_PATH is very special and many things does not work in this condition from my experience." → closing.
