### ISSUE TITLE
segfault from XrdXrootdProtocol::do_OffloadIO

### ISSUE THREAD

**Issue by snafus** [xrootd/xrootd#1821]
Hi,
  In XRootD 5.5.0 we recently observed a number of core dumps on a few of our production hosts. 
(The crashes occur at very similar times across a subset of the hosts). 

xrootd[2076890]: segfault at 1010 ip 00007f3148c49d00 sp 00007f312abfac68 error 4 in libpthread-2.17.so[7f3148c40000+17000]

The only information I unfortunately have is:
```
#0  0x00007f3148c49d00 in pthread_mutex_lock () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f3149e11a92 in Lock (this=0x2dc) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.hh:222
No locals.
#2  XrdXrootdProtocol::do_OffloadIO (this=0x4) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdXeq.cc:1290
        pioP = <optimized out>
        rc = 0
#3  0x00007f3149e0b343 in XrdXrootdProtocol::Process (this=0x7f30dd16d400, lp=<optimized out>) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:373
        rc = <optimized out>
#4  0x00007f3149b4e3e6 in XrdLinkXeq::DoIt (this=0x7f309ba88c50) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdLinkXeq.cc:320
        rc = <optimized out>
#5  0x00007f3149b514ca in XrdScheduler::Run (this=0x614e60 <XrdGlobal::Sched>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:406
        waiting = 18
        jp = 0x7f309ba88c50
#6  0x00007f3149b515e9 in XrdStartWorking (carg=<optimized out>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:89
        sp = <optimized out>
#7  0x00007f3149adf1e7 in XrdSysThread_Xeq (myargs=0x7f313140f0e0) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.cc:86
        ap = 0x7f313140f0e0
        retc = <optimized out>
#8  0x00007f3148c47ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#9  0x00007f314897098d in clone () from /lib64/libc.so.6
No symbol table info available.
```

Any thoughts appreciated, in what might be happening, and if a particular mode of operation is triggering this particular flow ?

James

**Comment by xrootd-dev** [comment]
A log around the time of the crash (at least two since you have multiple 
cores) may further help.

**Comment by snafus** [comment]
Hi, 
 If I look at the logs, then the consistent pattern is:
 ```
 221107 08:26:43 2808485 xrootd.2930604:21486@dtn17.nese.rc.fas.harvard.edu ofs_read: 16384@83869696 fn=/store/test/loadtest/source/T2_UK_SGrid_RALPP/urandom.270MB.file0001
221107 08:26:43 2808485 xrootd.2930604:21489@dtn17.nese.rc.fas.harvard.edu Xrootd_Response: 0500 sending final 8 info and 16400 data bytes
 ```
 
 ```
 221107 03:00:56 2717043 u1868.136:5645@[2605:9a00:10:200b:266e:96ff:fec6:5690] Xrootd_Protocol: 0100 request timeout; read 0 of 24 bytes
221107 03:00:56 2727481 xrootd.2930140:5614@dtn19.nese.rc.fas.harvard.edu ofs_read: 2093056@81776640 fn=/store/test/loadtest/source/T2_UK_London_IC/urandom.270MB.file0001
221107 03:00:56 2727481 xrootd.2930140:5646@dtn19.nese.rc.fas.harvard.edu Xrootd_Response: 0500 sending partial 8 info and 2095100 data bytes
221107 03:00:56 2727481 xrootd.2930140:5614@dtn19.nese.rc.fas.harvard.edu ofs_read: 16384@83869696 fn=/store/test/loadtest/source/T2_UK_London_IC/urandom.270MB.file0001
221107 03:00:56 2727481 xrootd.2930140:5646@dtn19.nese.rc.fas.harvard.edu Xrootd_Response: 0500 sending final 8 info and 16400 data bytes
```

```
221107 00:21:05 2649381 u2564.136:20450@[2605:9a00:10:200b:266e:96ff:fec6:5690] Xrootd_Protocol: 0100 request timeout; read 0 of 24 bytes
221107 00:21:05 2667083 xrootd.2927918:20364@dtn17.nese.rc.fas.harvard.edu ofs_read: 2093056@163569664 fn=/store/test/loadtest/source/T2_UK_SGrid_RALPP/urandom.270MB.file0001
221107 00:21:05 2667083 xrootd.2927918:20437@dtn17.nese.rc.fas.harvard.edu Xrootd_Response: 0500 sending partial 8 info and 2095100 data bytes
221107 00:21:06 2667083 xrootd.2927918:20364@dtn17.nese.rc.fas.harvard.edu ofs_read: 2093056@165662720 fn=/store/test/loadtest/source/T2_UK_SGrid_RALPP/urandom.270MB.file0001
221107 00:21:06 2667083 xrootd.2927918:20437@dtn17.nese.rc.fas.harvard.edu Xrootd_Response: 0500 sending partial 8 info and 2095100 data bytes
221107 00:21:06 2667083 xrootd.2927918:20364@dtn17.nese.rc.fas.harvard.edu ofs_read: 16384@167755776 fn=/store/test/loadtest/source/T2_UK_SGrid_RALPP/urandom.270MB.file0001
221107 00:21:06 2667083 xrootd.2927918:20437@dtn17.nese.rc.fas.harvard.edu Xrootd_Response: 0500 sending final 8 info and 16400 data bytes
```

 
James

**Comment by abh3** [comment]
OK, but should I assume it immediateoy crashes after the last log line 
here?

**Comment by snafus** [comment]
Yes, 
e.g.
```
221107 08:26:43 2808485 xrootd.2930604:21486@dtn17.nese.rc.fas.harvard.edu ofs_read: 16384@83869696 fn=/store/test/loadtest/source/T2_UK_SGrid_RALPP/urandom.270MB.file0001
221107 08:26:43 2808485 xrootd.2930604:21489@dtn17.nese.rc.fas.harvard.edu Xrootd_Response: 0500 sending final 8 info and 16400 data bytes
221107 08:27:03 2808906 Starting on Linux 3.10.0-1160.71.1.el7.x86_64
221107 08:27:03 2808906 /usr/bin/xrootd -d -l /var/log/xrootd/xrootd.log -c /etc/xrootd/xrootd-unified.cfg -k fifo -s /var/run/xrootd/xrootd-unified.pid -n unified
Copr.  2004-2012 Stanford University, xrd version v5.5.0
```

**Comment by abh3** [comment]
Any chance you can provide access to he core file?

**Comment by abh3** [comment]
A couple more things. This server, what is it? That is, a data flle server, proxy, Xcache? Could you also provide a link to he config file?

**Comment by abh3** [comment]
Let's start looking at the protocol object. So, with gdb please do the following

frame 3
print *this

and post the output here. Then let's continuebased on what we see.

**Comment by snafus** [comment]
Hi @abh3 , 
 Hope this is useful:
 
 ```
 (gdb) frame 3
#3  0x00007f370fa00343 in XrdXrootdProtocol::Process (this=0x7f36ba22a600, lp=<optimized out>) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:373
373	          else if ((rc = (*this.*Resume)()) != 0) return rc;
(gdb) print *this
$1 = {<XrdProtocol> = {<XrdJob> = {_vptr.XrdJob = 0x7f370fc91bc0 <vtable for XrdXrootdProtocol+16>, NextJob = 0x0, Comment = 0x7f370fa6b282 "xroot protocol handler", SchedTime = 0}, <No data fields>}, <XrdXrootd::gdCallBack> = {
    _vptr.gdCallBack = 0x7f370fc91c38 <vtable for XrdXrootdProtocol+136>}, <XrdSfsDio> = {_vptr.XrdSfsDio = 0x7f370fc91c68 <vtable for XrdXrootdProtocol+184>}, <XrdSfsXio> = {_vptr.XrdSfsXio = 0x7f370fc91ca0 <vtable for XrdXrootdProtocol+240>}, 
  static maxStreams = 16, static as_maxperlnk = 8, static as_maxperreq = 8, static as_maxpersrv = 4096, static as_miniosz = 98304, static as_minsfsz = 8192, static as_seghalf = 32768, static as_segsize = 65536, static as_maxstalls = 4, 
  static as_okstutter = 1, static as_timeout = 45, static as_force = false, static as_aioOK = false, static as_nosf = false, static as_syncw = false, static ProtStack = {<XrdJob> = {
      _vptr.XrdJob = 0x7f370fc91b98 <vtable for XrdObjectQ<XrdXrootdProtocol>+16>, NextJob = 0x7f370fc9a1c0 <XrdXrootdTransit::TranStack>, Comment = 0x7f370fa6b2ee "xroot protocol anchor", SchedTime = 1667995145}, QMutex = {cs = {__data = {
          __lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, First = 0x7f366cc4df38, Count = 10, Curage = 0, 
    MininQ = 21845, MaxinQ = 43690, Maxage = 3600, Sched = 0x614e60 <XrdGlobal::Sched>, Trace = 0x7f370fc99d00 <XrdXrootdTrace>, TraceON = 16, TraceID = 0x7f370fa6b304 "ProtStack"}, ProtLink = {Next = 0x7f3695050c38, Item = 0x7f36ba22a600, 
    QTime = 0}, static RPList = {next = 0x0, pathlen = 0, pathopt = 1, path = 0x7f370a879058 ""}, static RQList = {next = 0x0, pathlen = 0, pathopt = 1, path = 0x7f370a879060 ""}, static XPList = {next = 0x7f370a9dbfc0, pathlen = 2, pathopt = 8, 
    path = 0x7f370a879068 "*?"}, static osFS = 0x7f370fc9abc0 <XrdSfsGetDefaultFileSystem(XrdSfsFileSystem*, XrdSysLogger*, char const*, XrdOucEnv*)::XrdDefaultOfsFS>, static digFS = 0x0, static CIA = 0x7f370a871240, static DHS = 0x0, 
  static tlsCtx = 0x7f370a8791a0, static Locker = 0x7f3708ee2058, static Sched = 0x614e60 <XrdGlobal::Sched>, static BPool = 0x614bc0 <XrdGlobal::BuffPool>, static eDest = @0x7f370fc9a070, static PMark = 0x0, 
  static myInst = 0x7ffcb4c38f0d "unified", static TraceID = 0x7f370fa6b338 "Protocol", static RQLxist = 0, static myPID = 3514968, static myRole = -2145386495, static myRolf = 1, static myGID = 989, static myUID = 991, static myGNLen = 6, 
  static myUNLen = 6, static myGName = 0x7f370a879290 "xrootd", static myUName = 0x7f370a879288 "xrootd", static keepT = 86400, static AdminSock = 0x7f3708ecb1a0, static hailWait = 30000, static readWait = 3000, static Port = 1094, 
  static Window = 87380, static tlsPort = 0, static Notify = 0x7f3708ed7280 "%s://ceph-gw15.gridpp.rl.ac.uk:1094/&L=%d&U=%s", static myCName = 0x0, static myCNlen = 0, static isRedir = 0 '\000', static JobLCL = 0 '\000', 
  static JobCKCGI = 0 '\000', static JobCKS = 0x7f370a816580, static JobCKT = 0x7f370a879190 "adler32", static JobCKTLST = 0x7f370aa0d040, static PrepID = 0x7f370a8780b0, static fsFeatures = 17, static Route = {{Host = {0x0, 0x0}, Port = {0, 0}, 
      RDSz = {0, 0}} <repeats 18 times>}, static RouteClient = {Domain = {0x0, 0x0, 0x0, 0x0}, DomCnt = 0, pvtIP = false, lclDom = false}, static OD_Stall = 33, static OD_Bypass = false, static OD_Redir = false, static CL_Redir = false, 
  static isProxy = false, static usxMaxNsz = 248, static usxMaxVsz = 65536, static usxParms = 0x7f3708f04c90 "248 65536", static Req_TLSData = 1 '\001', static Req_TLSGPFile = 2 '\002', static Req_TLSLogin = 4 '\004', static Req_TLSSess = 8 '\b', 
  static Req_TLSTPC = 16 '\020', static tlsCap = 0 '\000', static tlsNot = 0 '\000', static maxBuffsz = 67108864, static maxTransz = 67108864, static SI = 0x7f370a83d3a0, numReads = 0, numReadP = 0, numReadV = 0, numSegsV = 0, numWritV = 0, 
  numSegsW = 0, numWrites = 0, numFiles = 0, cumReads = 0, cumReadP = 0, cumReadV = 0, cumSegsV = 0, cumWritV = 0, cumSegsW = 0, cumWrites = 0, myStalls = 0, totReadP = 0, Link = 0x7f368b71e468, argp = 0x7f36aa982d60, FTab = 0x0, Monitor = {
    Agent = 0x0, Did = 0, Iops = 0 '\000', Fops = 0 '\000', Len = 0, Name = 0x0}, pmHandle = 0x0, clientPV = -37747439, clientRN = 0, pmDone = false, reserved = "\000\000", rdType = 0, Status = 8 '\b', CapVer = 133 '\205', Client = 0x0, 
  AuthProt = 0x0, Entity = {prot = "host\000\000\000", prox = "\000\000\000\000\000\000\000", name = 0x0, host = 0x7f36a548e9c0 "dtn17.nese.rc.fas.harvard.edu", vorg = 0x0, role = 0x0, grps = 0x0, caps = 0x0, endorsements = 0x0, moninfo = 0x0, 
    creds = 0x0, credslen = 0, ueid = 0, addrInfo = 0x7f368b71e5a8, tident = 0x0, pident = 0x0, sessvar = 0x0, uid = 0, gid = 0, future = {0x0, 0x0, 0x0}, eaAPI = 0x7f369d991480}, Protect = 0x0, AppName = 0x0, sigReq2Ver = {header = {
      streamid = "\000", requestid = 0, body = '\000' <repeats 15 times>, dlen = 0}, auth = {streamid = "\000", requestid = 0, reserved = '\000' <repeats 11 times>, credtype = "\000\000\000", dlen = 0}, bind = {streamid = "\000", requestid = 0, 
      sessid = '\000' <repeats 15 times>, dlen = 0}, chkpoint = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", reserved = "\000\000\000\000\000\000\000\000\000\000", opcode = 0 '\000', dlen = 0}, chmod = {streamid = "\000", 
      requestid = 0, reserved = '\000' <repeats 13 times>, mode = 0, dlen = 0}, close = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", reserved = '\000' <repeats 11 times>, dlen = 0}, dirlist = {streamid = "\000", requestid = 0, 
      reserved = '\000' <repeats 14 times>, options = "", dlen = 0}, endsess = {streamid = "\000", requestid = 0, sessid = '\000' <repeats 15 times>, dlen = 0}, fattr = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", 
      subcode = 0 '\000', numattr = 0 '\000', options = 0 '\000', reserved = "\000\000\000\000\000\000\000\000", dlen = 0, static isNew = 1, static aData = 16}, gpfile = {streamid = "\000", requestid = 0, options = 0, 
      reserved = "\000\000\000\000\000\000\000", buffsz = 0, dlen = 0}, locate = {streamid = "\000", requestid = 0, options = 0, reserved = '\000' <repeats 13 times>, dlen = 0}, login = {streamid = "\000", requestid = 0, pid = 0, 
      username = "\000\000\000\000\000\000\000", ability2 = 0 '\000', ability = 0 '\000', capver = "", reserved2 = 0 '\000', dlen = 0}, mkdir = {streamid = "\000", requestid = 0, options = "", reserved = '\000' <repeats 12 times>, mode = 0, 
      dlen = 0}, mv = {streamid = "\000", requestid = 0, reserved = '\000' <repeats 13 times>, arg1len = 0, dlen = 0}, open = {streamid = "\000", requestid = 0, mode = 0, options = 0, reserved = '\000' <repeats 11 times>, dlen = 0}, pgread = {
      streamid = "\000", requestid = 0, fhandle = "\000\000\000", offset = 0, rlen = 0, dlen = 0}, pgwrite = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", offset = 0, pathid = 0 '\000', reqflags = 0 '\000', reserved = "\000", 
      dlen = 0}, ping = {streamid = "\000", requestid = 0, reserved = '\000' <repeats 15 times>, dlen = 0}, prepare = {streamid = "\000", requestid = 0, options = 0 '\000', prty = 0 '\000', port = 0, optionX = 0, 
      reserved = "\000\000\000\000\000\000\000\000\000", dlen = 0}, protocol = {streamid = "\000", requestid = 0, clientpv = 0, flags = 0 '\000', expect = 0 '\000', reserved = "\000\000\000\000\000\000\000\000\000", dlen = 0}, query = {
      streamid = "\000", requestid = 0, infotype = 0, reserved1 = "\000", fhandle = "\000\000\000", reserved2 = "\000\000\000\000\000\000\000", dlen = 0}, read = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", offset = 0, rlen = 0, 
      dlen = 0}, readv = {streamid = "\000", requestid = 0, reserved = '\000' <repeats 14 times>, pathid = 0 '\000', dlen = 0}, rm = {streamid = "\000", requestid = 0, reserved = '\000' <repeats 15 times>, dlen = 0}, rmdir = {streamid = "\000", 
      requestid = 0, reserved = '\000' <repeats 15 times>, dlen = 0}, set = {streamid = "\000", requestid = 0, reserved = '\000' <repeats 14 times>, modifier = 0 '\000', dlen = 0}, sigver = {streamid = "\000", requestid = 0, expectrid = 0, 
      version = 0 '\000', flags = 0 '\000', seqno = 0, crypto = 0 '\000', rsvd2 = "\000\000", dlen = 0}, stat = {streamid = "\000", requestid = 0, options = 0 '\000', reserved = "\000\000\000\000\000\000\000\000\000\000", fhandle = "\000\000\000", 
      dlen = 0}, sync = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", reserved = '\000' <repeats 11 times>, dlen = 0}, truncate = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", offset = 0, reserved = "\000\000\000", 
      dlen = 0}, write = {streamid = "\000", requestid = 0, fhandle = "\000\000\000", offset = 0, pathid = 0 '\000', reserved = "\000\000", dlen = 0}, writev = {streamid = "\000", requestid = 0, options = 0 '\000', 
      reserved = '\000' <repeats 14 times>, dlen = 0, static doSync = 1}}, sigReq = {header = {streamid = "\000", requestid = 0, body = '\000' <repeats 15 times>, dlen = 0}, sigver = {streamid = "\000", requestid = 0, expectrid = 0, 
      version = 0 '\000', flags = 0 '\000', seqno = 0, crypto = 0 '\000', rsvd2 = "\000\000", dlen = 0}}, sigBuff = '\000' <repeats 63 times>, sigNeed = false, sigHere = false, sigRead = false, sigWarn = true, linkAioReq = {
    _m = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = 0}, <No data fields>}}, static srvrAioOps = {_m = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = 0}, <No data fields>}}, pgwCtl = 0x0, 
  myBuff = 0x7f36ba22a9c8 "", myBlen = 0, myBlast = 0, gdCtl = {iovNum = 0, iovNow = 0, {iovAdj = 0, BuffLen = 0, DumpLen = 0}, useCB = false, Status = 0 '\000', stalls = 0 '\000', linkWait = {_m = {<std::__atomic_base<unsigned char>> = {
          static _S_alignment = 1, _M_i = 0 '\000'}, <No data fields>}}, {iovVec = 0x0, Buffer = 0x0}, ioDType = 0x0, CallBack = 0x0, static inNone = 0, static inCallBk = 1, static inData = 2, static inDataIov = 3, static inDump = 4, 
    static Active = 1, static Terminate = 3}, wvInfo = 0x0, ResumePio = (int (XrdXrootdProtocol::*)(XrdXrootdProtocol * const)) 0x7f370fa16fb0 <XrdXrootdProtocol::do_PgRIO()>, 
  Resume = (int (XrdXrootdProtocol::*)(XrdXrootdProtocol * const)) 0x7f370fa069e0 <XrdXrootdProtocol::do_OffloadIO()>, IO = {File = 0x7f36f6e6f480, {Offset = 251641856, WVBytes = 251641856, EInfo = {251641856, 0}}, IOLen = 0, Flags = 0, 
    reserved = 0 '\000', Mode = 0 '\000', static useBasic = 0, static useMMap = 1, static useSF = 2}, static hcMax = 28657, hcPrev = 13, hcNext = 21, hcNow = 13, halfBSize = 1048576, unbindMutex = {cs = {__data = {__lock = 0, __count = 0, 
        __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, streamMutex = {cs = {__data = {__lock = 0, __count = 0, __owner = 0, 
        __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, reTry = 0x0, endNote = 0x0, Stream = {0x7f36958bb000, 0x0 <repeats 15 times>}, mySID = 0, 
  isActive = true, isLinkWT = false, isNOP = false, isDead = false, static maxPio = 4, pioFirst = 0x7f36a8634bc0, pioLast = 0x7f3674045700, pioFree = 0x7f36ba253a80, PathID = 1, newPio = false, rvSeq = 0 '\000', wvSeq = 0 '\000', doTLS = 0 '\000', 
  ableTLS = true, isTLS = false, static PrepareAlt = false, static LimitError = true, PrepareCount = 0, static PrepareLimit = -1, ReqID = {Req = {ID = 318252781666909, ids = {Linst = 605, Lid = 8563, Sid = "\001"}}}, Request = {header = {
      streamid = "\000", requestid = 3024, body = "b\002\000\000X\242\065\000x!\000\000b\002\000", dlen = 0}, auth = {streamid = "\000", requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000", credtype = "b\002\000", dlen = 0}, bind = {
      streamid = "\000", requestid = 3024, sessid = "b\002\000\000X\242\065\000x!\000\000b\002\000", dlen = 0}, chkpoint = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", reserved = "X\242\065\000x!\000\000b\002", opcode = 0 '\000', 
      dlen = 0}, chmod = {streamid = "\000", requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002", mode = 0, dlen = 0}, close = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", 
      reserved = "X\242\065\000x!\000\000b\002\000", dlen = 0}, dirlist = {streamid = "\000", requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002", options = "", dlen = 0}, endsess = {streamid = "\000", requestid = 3024, 
      sessid = "b\002\000\000X\242\065\000x!\000\000b\002\000", dlen = 0}, fattr = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", subcode = 88 'X', numattr = 162 '\242', options = 53 '5', reserved = "\000x!\000\000b\002\000", 
      dlen = 0, static isNew = 1, static aData = 16}, gpfile = {streamid = "\000", requestid = 3024, options = 610, reserved = "X\242\065\000x!\000", buffsz = 610, dlen = 0}, locate = {streamid = "\000", requestid = 3024, options = 610, 
      reserved = "\000\000X\242\065\000x!\000\000b\002\000", dlen = 0}, login = {streamid = "\000", requestid = 3024, pid = 610, username = "X\242\065\000x!\000", ability2 = 98 'b', ability = 2 '\002', capver = "", reserved2 = 0 '\000', dlen = 0}, 
    mkdir = {streamid = "\000", requestid = 3024, options = "b", reserved = "\002\000\000X\242\065\000x!\000\000b\002", mode = 0, dlen = 0}, mv = {streamid = "\000", requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002", 
---Type <return> to continue, or q <return> to quit---
      arg1len = 0, dlen = 0}, open = {streamid = "\000", requestid = 3024, mode = 610, options = 0, reserved = "X\242\065\000x!\000\000b\002\000", dlen = 0}, pgread = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", 
      offset = 36799283307096, rlen = 610, dlen = 0}, pgwrite = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", offset = 36799283307096, pathid = 98 'b', reqflags = 2 '\002', reserved = "\000", dlen = 0}, ping = {streamid = "\000", 
      requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002\000", dlen = 0}, prepare = {streamid = "\000", requestid = 3024, options = 98 'b', prty = 2 '\002', port = 0, optionX = 41560, reserved = "5\000x!\000\000b\002\000", 
      dlen = 0}, protocol = {streamid = "\000", requestid = 3024, clientpv = 610, flags = 88 'X', expect = 162 '\242', reserved = "5\000x!\000\000b\002\000", dlen = 0}, query = {streamid = "\000", requestid = 3024, infotype = 610, 
      reserved1 = "\000", fhandle = "X\242\065", reserved2 = "x!\000\000b\002\000", dlen = 0}, read = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", offset = 36799283307096, rlen = 610, dlen = 0}, readv = {streamid = "\000", 
      requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002", pathid = 0 '\000', dlen = 0}, rm = {streamid = "\000", requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002\000", dlen = 0}, rmdir = {
      streamid = "\000", requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002\000", dlen = 0}, set = {streamid = "\000", requestid = 3024, reserved = "b\002\000\000X\242\065\000x!\000\000b\002", modifier = 0 '\000', dlen = 0}, 
    sigver = {streamid = "\000", requestid = 3024, expectrid = 610, version = 0 '\000', flags = 0 '\000', seqno = 36799283307096, crypto = 98 'b', rsvd2 = "\002\000", dlen = 0}, stat = {streamid = "\000", requestid = 3024, options = 98 'b', 
      reserved = "\002\000\000X\242\065\000x!\000", fhandle = "b\002\000", dlen = 0}, sync = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", reserved = "X\242\065\000x!\000\000b\002\000", dlen = 0}, truncate = {streamid = "\000", 
      requestid = 3024, fhandle = "b\002\000", offset = 36799283307096, reserved = "b\002\000", dlen = 0}, write = {streamid = "\000", requestid = 3024, fhandle = "b\002\000", offset = 36799283307096, pathid = 98 'b', reserved = "\002\000", 
      dlen = 0}, writev = {streamid = "\000", requestid = 3024, options = 98 'b', reserved = "\002\000\000X\242\065\000x!\000\000b\002\000", dlen = 0, static doSync = 1}}, Response = {Bridge = 0x0, Resp = {streamid = "\005", status = 0, 
      dlen = 16777216}, Link = 0x7f368b71e468, RespIO = {{iov_base = 0x7f36ba22a9e8, iov_len = 8}, {iov_base = 0x7f363fdfdbd0, iov_len = 1}, {iov_base = 0x7f369d851c60, iov_len = 102}}, trsid = "0500 \000\000", 
    static TraceID = 0x7f370fa6b78b "Response"}}
```

**Comment by abh3** [comment]
The problem appears to be related to the Ceph plugin with a parallel stream is used. This is being investigated by RAL. In the mean time they are using a custom source build that indicates that parallel streams are not supported which avoids the SEGV and provides some breathing room until the actual problem can be diagnosed. So, I am closing this and will reopen it should the problem wind up on the xrootd side after all.

**Comment by ijjorama** [comment]
Hi, At RAL we've noticed that using the Ceph plugin with XRootD v5.5.4.post257 doesn't cause a SEGV or any other problem. Do you know if there have been any changes in the multiple stream handling we might thank for this outcome?

**Comment by amadio** [comment]
Sorry, there have been several fixes applied in the last few releases. I am not sure which commit may have fixed this particular issue, but a look at the few last release notes may help to identify it.
