### ISSUE TITLE
XrdCl client crash on connection failure

### ISSUE THREAD

**Issue by smithdh** [xrootd/xrootd#1934]
Hi. The crashes below were seen in an application, 'eoscp', inside libXrdCl (eos build of xrootd, approx XRootD version 5.5.2). Believed to be in the situation where an XRootD server (the local machine on which the eoscp was running and where it was connecting to) was immediately closing connections, due to #1928. The server has two addresses (ipv4 and ipv6).

Most frequently at this location:

```
(gdb) bt
#0  XrdCl::XRootDTransport::GetHeader (this=<optimized out>, message=..., socket=0x2c021c7330) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:323
#1  0x00007f90c87f1115 in XrdCl::AsyncHSReader::Read (this=0x7f90b0000960) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncHSReader.hh:90
#2  XrdCl::AsyncSocketHandler::OnReadWhileHandshaking (this=0x21c7d00) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:515
#3  0x00007f90c87f226d in XrdCl::AsyncSocketHandler::Event (this=0x21c7d00, type=1 '\001') at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:227
#4  0x00007f90c87673d8 in (anonymous namespace)::SocketCallBack::Event (this=0x7f90b0000d70, chP=<optimized out>, cbArg=<optimized out>, evFlags=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClPollerBuiltIn.cc:83
#5  0x00007f90c99f07db in XrdSys::IOEvents::Poller::CbkXeq (this=0x21a68c0, cP=0x7f90b0000d90, events=1, eNum=<optimized out>, eTxt=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEvents.cc:721
#6  0x00007f90c99f1b03 in XrdSys::IOEvents::PollE::Dispatch (this=this@entry=0x21a68c0, cP=0x7f90b0000d90, pollEv=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEventsPollE.icc:275
#7  0x00007f90c99f1ce0 in XrdSys::IOEvents::PollE::Begin (syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>, this=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEventsPollE.icc:230
#8  XrdSys::IOEvents::PollE::Begin (this=0x21a68c0, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEventsPollE.icc:196
#9  0x00007f90c99ee3bd in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffe8a756290) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEvents.cc:149
#10 0x00007f90c99f6e27 in XrdSysThread_Xeq (myargs=0x21a6990) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysPthread.cc:86
#11 0x00007f90c73d1ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f90c70fab0d in clone () from /lib64/libc.so.6
```

and (less frequently) at this location:

```
(gdb) bt
#0  0x00007f2f4aab5562 in XrdCl::XRootDTransport::ProcessServerHS (this=<optimized out>, hsData=0x7f2f2c0008c0, info=0x2ada340) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:1876
#1  0x00007f2f4aabb213 in XrdCl::XRootDTransport::HandShakeMain (this=0x2ab7e00, handShakeData=0x7f2f2c0008c0, channelData=...) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:476
#2  0x00007f2f4aabb693 in XrdCl::XRootDTransport::HandShake (this=0x2ab7e00, handShakeData=0x7f2f2c0008c0, channelData=...) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:444
#3  0x00007f2f4ab28d33 in XrdCl::AsyncSocketHandler::OnConnectionReturn (this=0x2ada8e0) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:341
#4  0x00007f2f4ab2e1d1 in XrdCl::AsyncSocketHandler::Event (this=0x2ada8e0, type=4 '\004') at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:251
```

**Comment by smithdh** [comment]
Was (awkwardly) reproducible on a dual address machine, with 5.5.3, with this procedure:

localmachine# ulimit -c unlimited
localmachine# while [ 1 ]; do XRD_PARALLELEVTLOOP=10 XRD_CONNECTIONRETRY=0 jemalloc.sh xrdcp -f root://localmachine.cern.ch:8000//decjdjdj /dev/null ; done 

(while in another window(s) on localmachine.cern.ch):

while [ 1 ]; do nc -6 -l 8000 < /dev/null > /dev/null ; done
while [ 1 ]; do nc -4 -l 8000 < /dev/null > /dev/null ; done

Reproduced crash was of the second form of the traces shown in the first comment, above.
