### ISSUE TITLE
Host-based access in authdb causes segfault

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1986]
See backtrace below.

It appears the HTTP protocol doesn't set `Entity.addrInfo` and `XrdAccAccess::Resolve` is missing a null pointer check.

```
(gdb) bt 7
#0  XrdNetAddrInfo::Name (this=0x0, eName=eName@entry=0x7ffff7fc0658 "?", 
    eText=eText@entry=0x0)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdNet/XrdNetAddrInfo.cc:308
#1  0x00007ffff7fa24ab in XrdAccAccess::Resolve (Entity=Entity@entry=0x7fffe000e6c8)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdAcc/XrdAccAccess.cc:343
#2  0x00007ffff7fa2bf4 in XrdAccAccess::Access(XrdSecEntity const*, char const*, Access_Operation, XrdOucEnv*) () at /home/cse496/bbockelm/projects/xrootd/src/XrdAcc/XrdAccAccess.cc:167
#3  0x00007ffff7e5c524 in XrdAccSciTokens::Access (this=0x482370, Entity=0x7fffe000e6c8, 
    path=0x7fffe000ed98 "/metrics", oper=AOP_Read, env=0x0)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdSciTokens/XrdSciTokensAccess.cc:465
#4  0x00007ffff7e3acd1 in Macaroons::Authz::Access(XrdSecEntity const*, char const*, Access_Operation, XrdOucEnv*) ()
    at /home/cse496/bbockelm/projects/xrootd/src/XrdMacaroons/XrdMacaroonsAuthz.cc:199
#5  0x00007fffed51be42 in XrdPrometheus::Handler::ProcessReq(XrdHttpExtReq&) ()
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/basic_string.h:5195
#6  0x00007ffff7ea6475 in XrdHttpReq::ProcessHTTPReq() [clone .localalias] ()
    at /home/cse496/bbockelm/projects/xrootd/src/XrdHttp/XrdHttpReq.cc:984
```

**Comment by bbockelm** [comment]
Same issue appears to occur for the protocol bridge:

```
#0  0x00007ffff7cf30b4 in XrdNetAddrInfo::Name (this=0x0, eName=0x7ffff7fb9067 "?", 
    eText=0x0) at /home/cse496/bbockelm/projects/xrootd/src/XrdNet/XrdNetAddrInfo.cc:308
#1  0x00007ffff7f8c0be in XrdAccAccess::Resolve (Entity=0x7fffec873ad0)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdAcc/XrdAccAccess.cc:343
#2  0x00007ffff7f8b6ee in XrdAccAccess::Access (this=0x46b9a0, Entity=0x7fffec873ad0, 
    path=0x7fffe000fc00 "/tmp/stash/hello_world", oper=AOP_Stat, Env=0x7fffec873e20)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdAcc/XrdAccAccess.cc:167
#3  0x00007ffff0aa1b38 in XrdAccSciTokens::OnMissing (this=0x48a320, Entity=0x7fffec873ad0, 
    path=0x7fffe000fc00 "/tmp/stash/hello_world", oper=AOP_Stat, env=0x7fffec873e20)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdSciTokens/XrdSciTokensAccess.cc:687
#4  0x00007ffff0aa0e4a in XrdAccSciTokens::Access (this=0x48a320, Entity=0x7fffe000e6c8, 
    path=0x7fffe000fc00 "/tmp/stash/hello_world", oper=AOP_Stat, env=0x7fffec873e20)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdSciTokens/XrdSciTokensAccess.cc:553
#5  0x00007ffff0a539d0 in Macaroons::Authz::OnMissing (this=0x48c280, 
    Entity=0x7fffe000e6c8, path=0x7fffe000fc00 "/tmp/stash/hello_world", oper=AOP_Stat, 
    env=0x7fffec873e20)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdMacaroons/XrdMacaroonsAuthz.cc:153
#6  0x00007ffff0a53c39 in Macaroons::Authz::Access (this=0x48c280, Entity=0x7fffe000e6c8, 
    path=0x7fffe000fc00 "/tmp/stash/hello_world", oper=AOP_Stat, env=0x7fffec873e20)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdMacaroons/XrdMacaroonsAuthz.cc:199
#7  0x00007ffff7f445d8 in XrdOfs::stat (
    this=0x7ffff7ff01a0 <XrdSfsGetDefaultFileSystem(XrdSfsFileSystem*, XrdSysLogger*, char const*, XrdOucEnv*)::XrdDefaultOfsFS>, path=0x7fffe000fc00 "/tmp/stash/hello_world", 
    buf=0x7fffec8746f0, einfo=..., client=0x7fffe000e6c8, 
    info=0x7fffe000fc17 "authz=Bearer%20eyJhbGciOiJSUzI1NiIsImtpZCI6ImtleS1yczI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYm9ja2VsbSIsImF1ZCI6IkFOWSIsInZlciI6InNjaXRva2VuOjIuMCIsInNjb3BlIjoicmVhZDovdG1wL3N0YXNoIiwiaXNzIjoiaHR0cHM6Ly9k"...)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdOfs/XrdOfs.cc:2369
#8  0x00007ffff7f31380 in XrdXrootdProtocol::do_Stat (this=0x7fffe000edf8)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdXrootd/XrdXrootdXeq.cc:2899
#9  0x00007ffff7f184cc in XrdXrootdProtocol::Process2 (this=0x7fffe000edf8)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:595
#10 0x00007ffff7f215e7 in XrdXrootdTransit::Process (this=0x7fffe000edf0, lp=0x7fffe00082a0)
    at /home/cse496/bbockelm/projects/xrootd/src/XrdXrootd/XrdXrootdTransit.cc:375
#11 0x00007ffff7d4601e in XrdLinkXeq::DoIt (this=0x7fffe00082a0)
    at /home/cse496/bbockelm/projects/xrootd/src/Xrd/XrdLinkXeq.cc:320
#12 0x00007ffff7d434ce in XrdLink::setProtocol (this=0x7fffe00082a0, pp=0x7fffece77d00, 
    runit=true, push=false) at /home/cse496/bbockelm/projects/xrootd/src/Xrd/XrdLink.cc:435
```
