### ISSUE TITLE
xrdfs ls on a directory on a server runs locate

### ISSUE THREAD

**Issue by osschar** [xrootd/xrootd#2120]
While trying to demonstrate the most trivial server config, i.e.:
```
all.export /pelican
oss.localroot /data
```
and running `xrdfs localhost:1094 ls -l /pelican`, the server errored out as:
```
231109 15:30:16 214512 XrootdXeq: matevz.214661:26@[::ffff:127.0.0.1] pvt IPv4 login
231109 15:30:16 214512 ofs_fsctl: matevz.214661:26@[::ffff:127.0.0.1] Unable to locate /pelican/; network is unreachable
231109 15:30:16 214512 XrootdXeq: matevz.214661:26@[::ffff:127.0.0.1] disc 0:00:00
```

It turns out `xrdfs` seems to be calling `kXR_locate`, not `kXR_dirlist` which I would have expected to happen on a server, see backtrace [1] below.

`ls -l` of files (not directories) works ok.

The same problem happens when accessing the server via its private IPv4 address ... but it works ok if using localhost6 or its name that resolves to an IPv6 address. Note that only an AAAA record exists for the host, not AAA.

Now, if the server has chosen to also listen for v4 connections, it should presumably also know how to talk to itself via IPv4 ... or talk to itself via the properly configured interface :)

But, more importantly, why does xrdfs have to call `locate` when it knows it is talking to a server and not a redirector? Or should it be the server itself that filters out the locate flag, apparently passed from here:
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClFS.cc#L348

[1]
```
bt
#0  XrdOfs::Emsg (pfx=0x7ffff7f82558 "fsctl", einfo=..., ecode=101, op=0x7ffff7f8257e "locate", target=0x7fffe800f801 "/pelican/") at /foo/home/matevz/xrd-blk/xrootd/src/XrdOfs/XrdOfs.cc:2536
#1  0x00007ffff7f282e8 in XrdOfs::fsctl (this=0x7ffff7fb8ae0 <XrdSfsGetDefaultFileSystem(XrdSfsFileSystem*, XrdSysLogger*, char const*, XrdOucEnv*)::XrdDefaultOfsFS>, cmd=37814273, args=0x7fffe800f800 "*/pelican/", einfo=..., client=0x7fffe800f308) at /foo/home/matevz/xrd-blk/xrootd/src/XrdOfs/XrdOfsFSctl.cc:171
#2  0x00007ffff7ef31ec in XrdXrootdProtocol::do_Locate (this=0x7fffe800f210) at /foo/home/matevz/xrd-blk/xrootd/src/XrdXrootd/XrdXrootdXeq.cc:937
#3  0x00007ffff7ee3b2a in XrdXrootdProtocol::Process2 (this=0x7fffe800f210) at /foo/home/matevz/xrd-blk/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:589
#4  0x00007ffff7ee3128 in XrdXrootdProtocol::Process (this=0x7fffe800f210, lp=0x7fffe80063f0) at /foo/home/matevz/xrd-blk/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:430
#5  0x00007ffff7bb94be in XrdLinkXeq::DoIt (this=0x7fffe80063f0) at /foo/home/matevz/xrd-blk/xrootd/src/Xrd/XrdLinkXeq.cc:320
#6  0x00007ffff7bb6974 in XrdLink::setProtocol (this=0x7fffe80063f0, pp=0x7fffffffdb70, runit=true, push=false) at /foo/home/matevz/xrd-blk/xrootd/src/Xrd/XrdLink.cc:435
#7  0x0000000000414ef1 in XrdMain::DoIt (this=0x7fffffffdc70) at /foo/home/matevz/xrd-blk/xrootd/src/Xrd/XrdMain.cc:99
#8  0x00007ffff7bbfd8f in XrdScheduler::Run (this=0x41d8e0 <XrdGlobal::Sched>) at /foo/home/matevz/xrd-blk/xrootd/src/Xrd/XrdScheduler.cc:406
#9  0x00007ffff7bbebfc in XrdStartWorking (carg=0x41d8e0 <XrdGlobal::Sched>) at /foo/home/matevz/xrd-blk/xrootd/src/Xrd/XrdScheduler.cc:89
#10 0x00007ffff7b05b8a in XrdSysThread_Xeq (myargs=0x7fffe0000b70) at /foo/home/matevz/xrd-blk/xrootd/src/XrdSys/XrdSysPthread.cc:86
#11 0x00007ffff74ae947 in start_thread () from /lib64/libc.so.6
#12 0x00007ffff7534860 in clone3 () from /lib64/libc.so.6

fr 3
#3  0x00007ffff7ee3b2a in XrdXrootdProtocol::Process2 (this=0x7fffe800f210) at /foo/home/matevz/xrd-blk/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:589
589	          case kXR_locate:    return do_Locate();
```

**Comment by amadio** [comment]
Possibly related to #1565.
