### ISSUE TITLE
segfault around InitTLS()

### ISSUE THREAD

**Issue by smithdh** [xrootd/xrootd#2220]
Hello,

Recently have seen a segfault as below, apparently within XrdCl (in this case the application was EOS's fuse daemon "eosxd"), using eos-xrootd 5.6.8:

```
:#0  0x00007f0524db7395 in sk_num () from /lib64/libcrypto.so.10
:#1  0x00007f0524dfa568 in X509_STORE_free () from /lib64/libcrypto.so.10
:#2  0x00007f05251378ba in SSL_CTX_free () from /lib64/libssl.so.10
:#3  0x00007f0526f09359 in ~XrdTlsContextImpl (this=<optimized out>, __in_chrg=<optimized out>) at /usr/src/debug/xrootd-5.6.8/src/XrdTls/XrdTlsContext.cc:56
:#4  XrdTlsContext::~XrdTlsContext (this=0x7f04e7012058, __in_chrg=<optimized out>) at /usr/src/debug/xrootd-5.6.8/src/XrdTls/XrdTlsContext.cc:782
:#5  0x00007f05272f1130 in operator() (this=<optimized out>, __ptr=0x7f04e7012058) at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClTls.cc:125
:#6  operator() (this=0x7f0527614ce8 <tlsContext>, __ptr=0x7f04e7012058) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/unique_ptr.h:75
:#7  reset (__p=0x7f04e7012058, this=0x7f0527614ce8 <tlsContext>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/unique_ptr.h:382
:#8  operator= (__u=<optimized out>, this=0x7f0527614ce8 <tlsContext>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/unique_ptr.h:289
:#9  XrdCl::InitTLS() () at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClTls.cc:125
:#10 0x00007f0527304955 in XrdCl::XRootDTransport::InitProtocolReq(ClientProtocolRequest*, XrdCl::XRootDChannelInfo*, unsigned char) () at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClXRootDTransport.cc:1931
:#11 0x00007f0527304af8 in XrdCl::XRootDTransport::GenerateInitialHSProtocol (this=this@entry=0x7f04f7c653a0, hsData=hsData@entry=0x7f04e740e060, info=info@entry=0x7f04f7ca7180, expect=expect@entry=3 '\003') at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClXRootDTransport.cc:1869
:#12 0x00007f052730c2bb in XrdCl::XRootDTransport::HandShakeMain(XrdCl::HandShakeData*, XrdCl::AnyObject&) () at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClXRootDTransport.cc:507
:#13 0x00007f052730c903 in XrdCl::XRootDTransport::HandShake(XrdCl::HandShakeData*, XrdCl::AnyObject&) () at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClXRootDTransport.cc:486
:#14 0x00007f052737a5e3 in XrdCl::AsyncSocketHandler::OnConnectionReturn() () at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClAsyncSocketHandler.cc:377
:#15 0x00007f052737fea9 in EventWrite (type=4 '\004', this=0x7f04f7ca7300) at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClAsyncSocketHandler.cc:283
:#16 XrdCl::AsyncSocketHandler::Event(unsigned char, XrdCl::Socket*) () at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClAsyncSocketHandler.cc:227
:#17 0x00007f05272f39d8 in (anonymous namespace)::SocketCallBack::Event(XrdSys::IOEvents::Channel*, void*, int) () at /usr/src/debug/xrootd-5.6.8/src/XrdCl/XrdClPollerBuiltIn.cc:83
:#18 0x00007f0526f0072b in XrdSys::IOEvents::Poller::CbkXeq(XrdSys::IOEvents::Channel*, int, int, char const*) () at /usr/src/debug/xrootd-5.6.8/src/XrdSys/XrdSysIOEvents.cc:721
:#19 0x00007f0526f01a53 in XrdSys::IOEvents::PollE::Dispatch (this=this@entry=0x7f04f7c5f1e0, cP=0x7f04f7c63340, pollEv=<optimized out>) at /usr/src/debug/xrootd-5.6.8/src/XrdSys/XrdSysIOEventsPollE.icc:275
:#20 0x00007f0526f01c30 in Begin (syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>, this=<optimized out>) at /usr/src/debug/xrootd-5.6.8/src/XrdSys/XrdSysIOEventsPollE.icc:230
:#21 XrdSys::IOEvents::PollE::Begin (this=0x7f04f7c5f1e0, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /usr/src/debug/xrootd-5.6.8/src/XrdSys/XrdSysIOEventsPollE.icc:196
:#22 0x00007f0526efe30d in XrdSys::IOEvents::BootStrap::Start(void*) () at /usr/src/debug/xrootd-5.6.8/src/XrdSys/XrdSysIOEvents.cc:149
:#23 0x00007f0526f06d77 in XrdSysThread_Xeq (myargs=0x7f04f7c3e9a0) at /usr/src/debug/xrootd-5.6.8/src/XrdSys/XrdSysPthread.cc:86
:#24 0x00007f051f7c1ea5 in start_thread () from /lib64/libpthread.so.0
:#25 0x00007f051f4eab0d in clone () from /lib64/libc.so.6
```

and a few other segfaults somewhat similar traces. (Already discussed with Guilherme, hopefully the cause was understood).

**Comment by amadio** [comment]
Thanks, @smithdh! I've pushed the commit with the fix to devel, this will be in 5.7.0.
