### ISSUE TITLE
[XrdCms] improved load balancing algorithm for SelbyLoad

### ISSUE THREAD

**Issue by Jo-stfc** [xrootd/xrootd#2240]
[#2239](https://github.com/xrootd/xrootd/pull/2239) PR to introduce a variant of weighted random load balancing algorithm for selection by load

**Comment by Jo-stfc** [comment]
@amadio could you have a look?

**Comment by amadio** [comment]
@Jo-stfc I see that the CI is failing, once it's green I will review. Thanks!

**Comment by Jo-stfc** [comment]
https://github.com/xrootd/xrootd/pull/2246 looks like the branch I put the original PR for was missing the CTest changes

**Comment by Jo-stfc** [comment]
I'm seeing odd errors around the load balancing after the os upgrade to rocky 8:
the primary redirector keeps crashing from malloc errors. Removing the custom LB change does not cause immediate crashes, but there seems some trouble freeing the memory as both memory and load kept increasing until a manual restart. @amadio @abh3 have you seen similar issues elsewhere?
```
#0  0x00007f2b411f3acf in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f2b2d035700 (LWP 1061811))]
Missing separate debuginfos, use: yum debuginfo-install xrootd-server-5.6.9-4.el8.x86_64
(gdb) bt
#0  0x00007f2b411f3acf in raise () from /lib64/libc.so.6
#1  0x00007f2b411c6ea5 in abort () from /lib64/libc.so.6
#2  0x00007f2b41234cc7 in __libc_message () from /lib64/libc.so.6
#3  0x00007f2b4123bfcc in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f2b4123db64 in _int_free () from /lib64/libc.so.6
#5  0x00007f2b412be4d0 in freeaddrinfo () from /lib64/libc.so.6
#6  0x00007f2b42360ace in XrdNetAddr::Set(char const*, int) () from /lib64/libXrdUtils.so.3
#7  0x0000559f0fef999d in XrdCmsNode::do_SelAvoid(XrdCmsRRData&, XrdCmsSelect&, char*, bool&) ()
#8  0x0000559f0fefcb8c in XrdCmsNode::do_Select(XrdCmsRRData&) ()
#9  0x0000559f0ff006e8 in XrdCmsProtocol::Execute(XrdCmsRRData&) ()
#10 0x0000559f0fef3a38 in XrdCmsJob::DoIt() ()
#11 0x00007f2b4239baea in XrdScheduler::Run() () from /lib64/libXrdUtils.so.3
#12 0x00007f2b4239bbed in XrdStartWorking(void*) () from /lib64/libXrdUtils.so.3
#13 0x00007f2b4231e15b in XrdSysThread_Xeq () from /lib64/libXrdUtils.so.3
#14 0x00007f2b415721ca in start_thread () from /lib64/libpthread.so.0
#15 0x00007f2b411dee73 in clone () from /lib64/libc.so.6
```

**Comment by Jo-stfc** [comment]
this also affected the same host after it was downgraded back to sl7, despite it having worked well since February

**Comment by Jo-stfc** [comment]
Hi Guilherme, yes the problem is happening with the version as in this PR. I suspect it has to do with the new and delete for the 'weighed' array. I'm compiling a version with scoped allocation (initializing to STMax within the SelbyLoad) and see if it works. Ideally I'd like to turn it into a class variable for the cluster but the locking behaviour needed is a bit tricky

**Comment by amadio** [comment]
Please give me a few days to produce the patch I intend to merge, I don't use allocations there. If that still has problems we can postpone merging to 5.8. But my hope is that without allocations we will not run into these issues. Cheers,

**Comment by Jo-stfc** [comment]
thanks. preliminary testing of the version without explicit allocation looks good. I'll run it for longer during working hours tomorrow and let you know if that was all that was needed for the fix

**Comment by Jo-stfc** [comment]
yes looks like removing explicit allocation solved it
