### ISSUE TITLE
segfault 11 error during GetHostId function 

### ISSUE THREAD

**Issue by geonmo** [xrootd/xrootd#2278]
Hello, XRootD developers.

Recently, our site received a lot of xrootd "pss" requests, and the xrootd daemon has been consistently segfaulting and making core dumps. (The service is not turned off, the daemon is restarted, so the service is fine. However, the core dump file creation was happening too many times, which was causing issues.)

The cause was something that didn't normally happen, but suddenly happened recently. 

We believe this is happening after the 25 May upgrade to 5.6.9-1, but we are not sure.

We provide gdb backtrace information from the core dump file below.

You are executing the command return pHostId; in the GetHostId function and it appears to terminate with a memory access error.

It's hard to check because the values are optimised out, but just in case, I'm uploading the core dump file to my cernbox (it's unlimited, so it's about 11GB).

Please check it out.

```bash
(gdb) backtrace
#0  _M_grab (__alloc2=..., __alloc1=..., this=<optimized out>) at /usr/src/debug/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:229
#1  std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fee7cbe4990, __str=<error reading variable: Cannot access memory at address 0xc>)
    at /usr/src/debug/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:173
#2  0x00007fef9260f52c in GetHostId (this=<optimized out>) at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClURL.hh:96
#3  XrdCl::AsyncVectorReader::Read (this=<optimized out>, socket=..., btsret=@0x7fee7cbe4af0: 13088) at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClAsyncVectorReader.hh:185
#4  0x00007fef925fa693 in XrdCl::XRootDMsgHandler::ReadMessageBody (this=<optimized out>, socket=0x7fed74006d70, bytesRead=@0x7fee7cbe4af0: 13088)
    at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClXRootDMsgHandler.cc:887
#5  0x00007fef926678d2 in XrdCl::AsyncMsgReader::Read (this=0x7fedb40a3210) at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClAsyncMsgReader.hh:195
#6  0x00007fef92666048 in XrdCl::AsyncSocketHandler::OnRead (this=this@entry=0x7fed74007730) at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClAsyncSocketHandler.cc:511
#7  0x00007fef926664c2 in EventRead (type=1 '\001', this=0x7fed74007730) at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClAsyncSocketHandler.cc:246
#8  XrdCl::AsyncSocketHandler::Event (this=0x7fed74007730, type=1 '\001') at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClAsyncSocketHandler.cc:224
#9  0x00007fef925c68b7 in (anonymous namespace)::SocketCallBack::Event (this=0x7fed3040ae10, chP=<optimized out>, cbArg=<optimized out>, evFlags=<optimized out>)
    at /usr/src/debug/xrootd-5.6.9/src/XrdCl/XrdClPollerBuiltIn.cc:83
#10 0x00007fef9c520d3b in XrdSys::IOEvents::Poller::CbkXeq (this=this@entry=0x7fef4803fde0, cP=cP@entry=0x7fed30100370, events=1, eNum=<optimized out>, eTxt=0x0)
    at /usr/src/debug/xrootd-5.6.9/src/XrdSys/XrdSysIOEvents.cc:721
#11 0x00007fef9c521f99 in XrdSys::IOEvents::PollE::Dispatch (this=this@entry=0x7fef4803fde0, cP=0x7fed30100370, pollEv=<optimized out>) at /usr/src/debug/xrootd-5.6.9/src/XrdSys/XrdSysIOEventsPollE.icc:275
#12 0x00007fef9c522170 in XrdSys::IOEvents::PollE::Begin (this=0x7fef4803fde0, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>)
    at /usr/src/debug/xrootd-5.6.9/src/XrdSys/XrdSysIOEventsPollE.icc:230
#13 0x00007fef9c51e6fd in XrdSys::IOEvents::BootStrap::Start (parg=0x7fef7a7ee710) at /usr/src/debug/xrootd-5.6.9/src/XrdSys/XrdSysIOEvents.cc:149
#14 0x00007fef9c5279c7 in XrdSysThread_Xeq (myargs=0x7fef4803feb0) at /usr/src/debug/xrootd-5.6.9/src/XrdSys/XrdSysPthread.cc:86
#15 0x00007fef9b68eea5 in start_thread (arg=0x7fee7cbe5700) at pthread_create.c:307
#16 0x00007fef9b3b7b0d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by geonmo** [comment]
I checked the date incorrectly, the upgrade happened on March 25th, and I don't think it has anything to do with the version.

**Comment by geonmo** [comment]
Here is a link to the core dump.

[Link](https://cernbox.cern.ch/s/XNFq2z1D6M7pThw)

**Comment by smithdh** [comment]
Hi @geonmo. There was recently a new xrootd release (v5.7.0); are you able to say yet if this issue is still seen when using 5.7.0?

Thank you, David.

**Comment by geonmo** [comment]
@smithdh Sorry for the late reply. Now, I updated xrootd to 5.7. I closed this issue now.
