### ISSUE TITLE
macos python venv :: libraries are not search in their location

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#2350]
So, i just tried on a macos the xrootd installation in a python venv .. the installation was successful but when trying to use i got this:
```
(alienpy_env) [Monday 07.10.24 20:51] asevcenc@aido2osx3 : ~/jalien_py/tests  (master) $ 
python3
Python 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from XRootD import client as xrd_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/XRootD/client/__init__.py", line 3, in <module>
    from .glob_funcs import glob, iglob
  File "/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/XRootD/client/glob_funcs.py", line 26, in <module>
    from XRootD.client.filesystem import FileSystem
  File "/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/XRootD/client/filesystem.py", line 26, in <module>
    from pyxrootd import client
ImportError: dlopen(/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/client.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libXrdCl.3.dylib
  Referenced from: <D1DB56E5-3132-331A-8258-FC1D938AD30D> /Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/client.cpython-312-darwin.so
  Reason: tried: '/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/../lib/libXrdCl.3.dylib' (no such file), '/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/../lib/libXrdCl.3.dylib' (no such file), '/usr/local/lib/libXrdCl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libXrdCl.3.dylib' (no such file), '/usr/local/lib/libXrdCl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libXrdCl.3.dylib' (no such file)
``` 

looking into `/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd` seems that all `.dylib` files are there .. 
```
(alienpy_env) [Monday 07.10.24 21:03] asevcenc@aido2osx3 : ~/jalien_py/tests  (master) $ 
ls /Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/libXrdCl.*
/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/libXrdCl.3.0.0.dylib
/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/libXrdCl.3.dylib
/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/libXrdCl.dylib
```

Any idea what could be the problem?
Thanks a lot!!

**Comment by amadio** [comment]
It looks like the `RPATH` is not set correctly:
```
  Reason: tried: '/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/../lib/libXrdCl.3.dylib' (no such file), '/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/../lib/libXrdCl.3.dylib' (no such file), '/usr/local/lib/libXrdCl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libXrdCl.3.dylib' (no such file), '/usr/local/lib/libXrdCl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libXrdCl.3.dylib' (no such file)
```
Notice the `../lib/libXrdCl.3.dylib` in there, but there's no `lib` directory in the installation. The workaround would be to set `DYLD_LIBRARY_PATH=/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd`, but I will check that the `RPATH` is set correctly and fix it if not. I thought I had it working last time I worked on this, however, setting an `RPATH` that works in all cases is not easy, so it's likely that the `RPATH` that works in other cases doesn't work in a venv.

**Comment by adriansev** [comment]
So, i tried also in the normal environment (no venv) and i got the same:
```
ImportError: dlopen(/Users/asevcenc/Library/Python/3.12/lib/python/site-packages/pyxrootd/client.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libXrdCl.3.dylib
  Referenced from: <D4150B60-D3B0-3BC1-A15D-9A2C676ACD32> /Users/asevcenc/Library/Python/3.12/lib/python/site-packages/pyxrootd/client.cpython-312-darwin.so
  Reason: tried: '/Users/asevcenc/Library/Python/3.12/lib/python/site-packages/pyxrootd/../lib/libXrdCl.3.dylib' (no such file), '/Users/asevcenc/Library/Python/3.12/lib/python/site-packages/pyxrootd/../lib/libXrdCl.3.dylib' (no such file), '/usr/local/lib/libXrdCl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libXrdCl.3.dylib' (no such file), '/usr/local/lib/libXrdCl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libXrdCl.3.dylib' (no such file)
```

otool output for no venv:
```
otool -L /Users/asevcenc/Library/Python/3.12/lib/python/site-packages/pyxrootd/libXrdCl.3.dylib
/Users/asevcenc/Library/Python/3.12/lib/python/site-packages/pyxrootd/libXrdCl.3.dylib:
        @rpath/libXrdCl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        @rpath/libXrdXml.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        @rpath/libXrdUtils.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
        /usr/local/opt/openssl@3/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/local/opt/openssl@3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.157.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

for the venv usage the output seems identical:
```
otool -L /Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/libXrdCl.3.dylib
/Users/asevcenc/alienpy_env/lib/python3.12/site-packages/pyxrootd/libXrdCl.3.dylib:
        @rpath/libXrdCl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        @rpath/libXrdXml.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        @rpath/libXrdUtils.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
        /usr/local/opt/openssl@3/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/local/opt/openssl@3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.157.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

**Comment by amadio** [comment]
Could you please paste here the commands you used to install in each case, so I can rerun them to reproduce a similar environment? Have you tried using XRootD from Homebrew? Thanks!

**Comment by adriansev** [comment]
so, on this machine i'm just a user, so i'm not sure if i can use the howebrew ... but anyway the intent would be to have something isolated ...
the actual commands were:
`python3 -m pip install --upgrade xrootd` within venv
and for user side no venv:
`python3 -m pip install --no-cache-dir --upgrade --user --break-system-packages xrootd`

i did not export anything nor set the environment in any way

**Comment by abh3** [comment]
I've also run into this problem. Depending on how the software is installed it might not wind up in the default search path or the default pat is not updated. I have never been able to successfully explain why this can happen not only on MacOS but in Linux as well.
________________________________

**Comment by amadio** [comment]
For the record, I just tried this on my (ancient) mac, and it worked:
```sh
amadio@jrochambp ~ % python3 --version
Python 3.12.5
amadio@jrochambp ~ % which python3
/usr/local/bin/python3
amadio@jrochambp ~ % python3 -m venv python3-xrootd
amadio@jrochambp ~ % source python3-xrootd/bin/activate
(python3-xrootd) amadio@jrochambp ~ % env CMAKE_PREFIX_PATH=/usr/local/opt/openssl@3 python3 -m pip install xrootd
Collecting xrootd
  Downloading xrootd-5.7.1.tar.gz (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 31.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: xrootd
  Building wheel for xrootd (pyproject.toml) ... done
  Created wheel for xrootd: filename=xrootd-5.7.1-cp312-cp312-macosx_11_0_x86_64.whl size=6379164 sha256=bb3e072a53ca3c6173d027f731fe396dac07791e11d4c5a1980684e847b1607c
  Stored in directory: /Users/amadio/Library/Caches/pip/wheels/45/13/da/3ac352b6b317bc3188ca56ac83d6985565ec3acd502be47275
Successfully built xrootd
Installing collected packages: xrootd
Successfully installed xrootd-5.7.1
(python3-xrootd) amadio@jrochambp ~ % python3 -m pip show xrootd                                         
Name: xrootd
Version: 5.7.1
Summary: eXtended ROOT daemon
Home-page: http://xrootd.org
Author: XRootD Developers
Author-email: xrootd-dev@slac.stanford.edu
License: LGPLv3+
Location: /Users/amadio/python3-xrootd/lib/python3.12/site-packages
Requires: 
Required-by: 
(python3-xrootd) amadio@jrochambp ~ % python3.12 -c 'from XRootD import client as xrd_client'                     
(python3-xrootd) amadio@jrochambp ~ % python3.12 -c 'from XRootD import client as xrd_client; print(xrd_client)'
<module 'XRootD.client' from '/Users/amadio/python3-xrootd/lib/python3.12/site-packages/XRootD/client/__init__.py'>
(python3-xrootd) amadio@jrochambp ~ % 
```

**Comment by amadio** [comment]
Nevermind, I could reproduce (and understand) this problem now. It was working for me before because of another installation of XRootD, which was resolving `@rpath/libXrdCl.3.dylib`. I uninstalled all other XRootD versions, so now I can see the problem too. I will fix it, thanks for reporting! As a workaround, you can do this to fix your installation:
```sh
install_name_tool -rpath '@loader_path/../lib' '@loader_path' /Users/asevcenc/Library/Python/3.12/lib/python/site-packages/pyxrootd/client.cpython-312-darwin.so
```
What is happening is that the `RPATH` set during installation is wrong. I do have

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/setup.py#L79-L82

in `setup.py`, which should set it correctly, but it unfortunately gets overriden by

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/cmake/XRootDOSDefs.cmake#L107-L113

which then sets the wrong value. The `set` command in `XRootDOSDefs.cmake` needs to set it in the cache so it doesn't override something set by the user during configuration.

**Comment by adriansev** [comment]
Thanks a lot @amadio !!!
