### ISSUE TITLE
XrdSecGSUL SEGV in secgsi_GetSrvCertEnt when a certificate entry is expired

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#401]
160802 07:11:04 21669 secgsi_GetSrvCertEnt: entry has expired: trying to renew ...\
triggers a SEGV with the following stack trace:

```
#5  <signal handler called>
#6  XrdCryptosslRSA::XrdCryptosslRSA (this=0x7f12b04c3be0, r=...) at /usr/src/debug/xrootd/xrootd/src/XrdCrypto/XrdCryptosslRSA.cc:152
#7  0x00000036992110a9 in XrdCryptosslFactory::RSA (this=<value optimized out>, r=...) at /usr/src/debug/xrootd/xrootd/src/XrdCrypto/XrdCryptosslFactory.cc:320
#8  0x00007f3d0ae1e13e in XrdSecProtocolgsi::ServerDoCertreq (this=0x7f12c1e69b80, br=0x7f12764e3cf0, bm=0x7f13da8c84d8, cmsg=...) at /usr/src/debug/xrootd/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:3360
#9  0x00007f3d0ae1e42d in XrdSecProtocolgsi::ParseServerInput (this=<value optimized out>, br=0x7f12764e3cf0, bm=0x7f13da8c84d8, cmsg=...) at /usr/src/debug/xrootd/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:3273
#10 0x00007f3d0ae1e844 in XrdSecProtocolgsi::Authenticate (this=0x7f12c1e69b80, cred=<value optimized out>, parms=0x7f13da8c8db8, ei=0x7f13da8c8530) at /usr/src/debug/xrootd/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:1697
#11 0x000000000041f9eb in XrdXrootdProtocol::do_Auth (this=0x7f2ce0dd0d00) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdXeq.cc:147
#12 0x000000369864ee69 in XrdLink::DoIt (this=0x7f2d1b70c008) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdLink.cc:442
#13 0x0000003698652d05 in XrdScheduler::Run (this=0x3697c0b900) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:307
#14 0x0000003698652ef9 in XrdStartWorking (carg=<value optimized out>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:84
#15 0x000000369862165f in XrdSysThread_Xeq (myargs=0x7f135445a680) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.cc:86
#16 0x0000003696607aa1 in start_thread () from /lib64/libpthread.so.0
#17 0x00000036962e8aad in clone () from /lib64/libc.so.6
```

This is XRootd 3.3.6-4
I couldn't find any newer commit touching this piece of code in XrootD 4.4.

**Comment by abh3** [comment]
Is this still an issue? I think it was fixed in the latest batch of gsi patches.

**Comment by gganis** [comment]
Hi Andy,

I guess the recent bunch of fixes should fix this too.
I suggest we close it and see how it goes. Though we need EOS to use the new version.

Gerri

**Comment by abh3** [comment]
I'm closing this as fixed.
