### ISSUE TITLE
XrdCl crash in AsyncSocketHandler::OnWrite

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#525]
Stacktrace from ALICE trying to push data to CASTOR using XRootD 4.5.0:

```bash
#0  0x0000000001e27e80 in ?? ()
#1  0x0000003d11492e65 in XrdCl::AsyncSocketHandler::OnWrite() () from
/usr/lib64/libXrdCl.so.2
#2  0x0000003d11444ab3 in ?? () from /usr/lib64/libXrdCl.so.2
#3  0x0000003d0fc2c2e8 in
XrdSys::IOEvents::Poller::CbkXeq(XrdSys::IOEvents::Channel*, int, int, char
const*) () from /usr/lib64/libXrdUtils.so.2
#4  0x0000003d0fc2c4b9 in
XrdSys::IOEvents::PollE::Dispatch(XrdSys::IOEvents::Channel*, unsigned int) ()
from /usr/lib64/libXrdUtils.so.2
#5  0x0000003d0fc2c743 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&,
char const**) () from /usr/lib64/libXrdUtils.so.2
#6  0x0000003d0fc2aefd in XrdSys::IOEvents::BootStrap::Start(void*) () from
/usr/lib64/libXrdUtils.so.2
#7  0x0000003d0fc28d7f in XrdSysThread_Xeq () from /usr/lib64/libXrdUtils.so.2
#8  0x0000003d0ec07aa1 in start_thread () from /lib64/libpthread.so.0
#9  0x0000003d0e4e8aad in clone () from /lib64/libc.so.6
```

**Comment by esindril** [comment]
This was fixed in 4.6.0.
