### ISSUE TITLE
Segv in SSI_WakeUp

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#580]
In the configuration where XRootD+SSI is fielding requests to the OFS plugin, under certain conditions, the WakeUp() function is called with a NULL pointer for the callback function. When XRootD tries to call this, it causes a segmentation fault.

Here is the backtrace:
```
#4  <signal handler called>
#5  0x00007f4d594bea9f in XrdSsiFileReq::WakeUp (this=this@entry=0x7f4d1003c650, aP=aP@entry=0x0) at /usr/src/debug/xrootd/xrootd/src/XrdSsi/XrdSsiFileReq.cc:981
#6  0x00007f4d594bf882 in XrdSsiFileReq::ProcessResponse (this=0x7f4d1003c650, eInfo=..., Resp=...) at /usr/src/debug/xrootd/xrootd/src/XrdSsi/XrdSsiFileReq.cc:555
#7  0x00007f4d58fe7616 in XrdSsiResponder::SetResponse (this=0x7f4d285e7ca0, buff=0x0, blen=0) at /usr/include/xrootd/private/XrdSsi/XrdSsiResponder.hh:250
#8  0x00007f4d58fe7517 in XrdSsiResponder::SetNilResponse (this=0x7f4d285e7ca0) at /usr/include/xrootd/private/XrdSsi/XrdSsiResponder.hh:234
#9  0x00007f4d58ff1f0d in XrdSsiPb::RequestProc<cta::xrd::Request, cta::xrd::Response, cta::xrd::Alert>::Execute (this=0x7f4d285e7ca0)
    at /usr/src/debug/cta-0-194916gite49e26b7/xroot_ssi_pb/XrdSsiPbRequestProc.hpp:183
#10 0x00007f4d58ff19a9 in XrdSsiPb::Service<cta::xrd::Request, cta::xrd::Response, cta::xrd::Alert>::ProcessRequest (this=0x2b08f20, reqRef=..., resRef=...)
    at /usr/src/debug/cta-0-194916gite49e26b7/xroot_ssi_pb/XrdSsiPbService.hpp:143
#11 0x00007f4d7e6ab3ff in XrdScheduler::Run (this=0x610e58 <XrdMain::Config+440>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:357
#12 0x00007f4d7e6ab549 in XrdStartWorking (carg=<optimized out>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:87
#13 0x00007f4d7e66b097 in XrdSysThread_Xeq (myargs=0x7f4d0c02ec90) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.cc:86
#14 0x00007f4d7e227dc5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f4d7d52d73d in clone () from /lib64/libc.so.6
```
The WakeUp call is called several times with a correct callback but finally with a NULL CB. With XRootD debug info enabled:
```
# grep WakeUp cta-frontend.log
170914 16:33:33 1133 root.1052:168@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=100a8000000cc
170914 16:33:40 1130 root.4891:140@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=1008c00000198
170914 16:33:42 1145 root.6067:129@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=10081000001d8
170914 16:33:46 1211 root.7170:144@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=1009000000233
170914 16:33:47 1223 root.6901:261@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=1010500000241
170914 16:33:50 1194 root.9749:153@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=1009900000286
170914 16:33:52 1229 root.11078:183@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=100b7000002af
170914 16:33:52 1193 root.11062:185@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=100b9000002b0
170914 16:33:53 1158 root.11288:129@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=10081000002b4
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=0
```
Here are the last few lines of the logfile:
```
170914 16:33:53 1158 root.11288:129@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=10081000002b4
170914 16:33:53 1227 XrdSched: running async response inq=0
170914 16:33:53 1227 root.11288:129@10.254.51.7 XrdLink: Setting ref to 1+1 post=0
170914 16:33:53 1227 root.11288:129@10.254.51.7 XrdLink: Setting ref to 2+-1 post=0
170914 16:33:53 1227 XrootdsendVesp: root.11288:129@10.254.51.7 async 0100  query status 0
170914 16:33:53 1227 root.11288:129@10.254.51.7 Ssi_Done: 0:/ctafrontend [bound odRsp] resp sent; no additional data remains
170914 16:33:53 1227 root.11288:129@10.254.51.7 Ssi_Finalize: 0:/ctafrontend [bound odRsp] Calling Finished(False)
170914 16:33:53 1158 root.11288:129@10.254.51.7 Ssi_Unbind: 0:/ctafrontend [bound odRsp] Recycling request...
170914 16:33:53 1195 root.11696:140@10.254.51.7 Ssi_write: 0:/ctafrontend rsz=55 wsz=55
170914 16:33:53 1195 root.11696:140@10.254.51.7 Ssi_Activate: 0:/ctafrontend [new wtReq] oucbuff rqsz=55
170914 16:33:53 1195 root.11696:140@10.254.51.7 XrootdResponse: 0100 sending OK
170914 16:33:53 1195 root.11696:140@10.254.51.7 XrootdProtocol: 0100 req=query dlen=8
170914 16:33:53 1195 root.11696:140@10.254.51.7 Ssi_fctl: 0:/ctafrontend query resp status
170914 16:33:53 1195 root.11696:140@10.254.51.7 Ssi_fctl: 0:/ctafrontend resp ready
170914 16:33:53 1195 root.11696:140@10.254.51.7 XrootdProtocol: 0100 query Qopaqug rc=-2048 fh=0
170914 16:33:53 1195 root.11696:140@10.254.51.7 XrootdResponse: 0100 sending 53 data bytes; status=0
170914 16:33:53 1161 XrdSched: running  inq=0
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_DoIt: 0:/ctafrontend [begun xqReq] Calling service processor
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_BindDone: 0:/ctafrontend [begun xqReq] Bind called; for request 0
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_GetRequest: 0:/ctafrontend [bound xqReq] sz=55
170914 16:33:53 1195 root.11696:140@10.254.51.7 Ssi_Done: 0:/ctafrontend [bound xqReq] wtrsp sent; resp pend
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_RelReqBuff: 0:/ctafrontend [bound xqReq] called
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_ProcessResponse: 0:/ctafrontend [bound xqReq] Response presented wtr=True
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_ProcessResponse: 0:/ctafrontend [bound doRsp] Resp data sz=0
170914 16:33:53 1161 root.11696:140@10.254.51.7 Ssi_WakeUp: 0:/ctafrontend [bound doRsp] respCBarg=0
170914 16:33:53 1180 XrdSched: running root.11288:129@10.254.51.7 inq=0
170914 16:33:53 1180 XrootdXeq: root.11288:129@10.254.51.7 disc 0:00:00
170914 16:33:53 1180 root.11288:129@10.254.51.7 XrootdFile: closing r /ctafrontend
170914 16:33:53 1180 root.11288:129@10.254.51.7 Ssi_close: /ctafrontend del=True
170914 16:33:53 1180 root.11288:129@10.254.51.7 XrdPoll: FD 129 detached from poller 1; num=0
170914 16:33:53 1195 XrootdXeq: root.11696:140@10.254.51.7 disc 0:00:00
170914 16:33:53 1195 root.11696:140@10.254.51.7 XrootdFile: closing r /ctafrontend
170914 16:33:53 1195 root.11696:140@10.254.51.7 Ssi_close: /ctafrontend del=True
170914 16:33:53 1195 root.11696:140@10.254.51.7 XrdPoll: FD 140 detached from poller 0; num=0
bash: line 1:  1072 Segmentation fault      (core dumped) xrootd -n cta -c /etc/xrootd/xrootd-cta.cfg -I v4 -d
```
The XRootD configuration is as follows:
```
xrootd.fslib libXrdSsi.so libXrdCtaOfs.so
ssi.fspath /Y3Rh
ssi.fspath /L3Vzci9iaW4vY3Rh
ssi.svclib libXrdSsiCta.so
xrootd.seclib libXrdSec.so
sec.protocol krb5 /etc/cta-frontend.krb5.keytab cta/cta-frontend@TEST.CTA
sec.protocol sss -s /etc/ctafrontend_SSS_s.keytab -c /etc/ctafrontend_SSS_c.keytab
sec.protbind * only sss krb5
all.export /ctafrontend nolock r/w
all.export /Y3Rh
all.export /L3Vzci9iaW4vY3Rh
xrootd.async off
xrd.port 10955
```
The failure is independent of whether we are calling the OFS or SSI plugins. It can be triggered by putting a heavy load on the server. When we try to do 1000 archive or delete operations, the first few hundred operations will succeed, then it will crash.

**Comment by abh3** [comment]
Ah, so this seems to be a race condition between the client deciding to give up and the ctafrontend posting a response at the same time. I need to look at the core file to see exactly what the circumstances are. There is a way around this race condition but I need to understand the exact sequence here and the core file will help. I will be at CERN next week and we can dive into this then

**Comment by abh3** [comment]
This has been resolved.
