### ISSUE TITLE
segfault in XrdOucHash<XrdCryptoX509Chain>::Find

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#661]
Have seen a spurious crash in what appears to be client-side GSI authentication:
```
backtrace:
:Core was generated by `/usr//bin/eosd /eos/atlas -obig_writes,max_readahead=131072,max_write=4194304,f'.
:Program terminated with signal 11, Segmentation fault.
:#0  0x00007f59c63ed4b3 in XrdOucHash<XrdCryptoX509Chain>::Find(char const*, long*) () from /usr/lib64/libXrdSecgsi-4.so
:#0  0x00007f59c63ed4b3 in XrdOucHash<XrdCryptoX509Chain>::Find(char const*, long*) () from /usr/lib64/libXrdSecgsi-4.so
:#1  0x00007f59c63e03ca in XrdSecProtocolgsi::GetCA(char const*, XrdCryptoFactory*, gsiHSVars*) () from /usr/lib64/libXrdSecgsi-4.so
:#2  0x00007f59c63e0cab in XrdSecProtocolgsi::ParseCAlist(XrdOucString) () from /usr/lib64/libXrdSecgsi-4.so
:#3  0x00007f59c63e8cba in XrdSecProtocolgsi::ClientDoInit(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&) () from /usr/lib64/libXrdSecgsi-4.so
:#4  0x00007f59c63e921d in XrdSecProtocolgsi::ParseClientInput(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&) () from /usr/lib64/libXrdSecgsi-4.so
:#5  0x00007f59c63e95ee in XrdSecProtocolgsi::getCredentials(XrdSecBuffer*, XrdOucErrInfo*) () from /usr/lib64/libXrdSecgsi-4.so
:#6  0x00007f59d96fc74c in XrdCl::XRootDTransport::GetCredentials(XrdSecBuffer*&, XrdCl::HandShakeData*, XrdCl::XRootDChannelInfo*) () from /usr/lib64/libXrdCl.so.2
:#7  0x00007f59d96fcd3a in XrdCl::XRootDTransport::DoAuthentication(XrdCl::HandShakeData*, XrdCl::XRootDChannelInfo*) () from /usr/lib64/libXrdCl.so.2
:#8  0x00007f59d96fdbc6 in XrdCl::XRootDTransport::HandShakeMain(XrdCl::HandShakeData*, XrdCl::AnyObject&) () from /usr/lib64/libXrdCl.so.2
:#9  0x00007f59d96fdd93 in XrdCl::XRootDTransport::HandShake(XrdCl::HandShakeData*, XrdCl::AnyObject&) () from /usr/lib64/libXrdCl.so.2
:#10 0x00007f59d9745065 in XrdCl::AsyncSocketHandler::OnReadWhileHandshaking() () from /usr/lib64/libXrdCl.so.2
:#11 0x00007f59d97452b8 in XrdCl::AsyncSocketHandler::Event(unsigned char, XrdCl::Socket*) () from /usr/lib64/libXrdCl.so.2
:#12 0x00007f59d96efbd3 in ?? () from /usr/lib64/libXrdCl.so.2
:#13 0x00007f59d943f338 in XrdSys::IOEvents::Poller::CbkXeq(XrdSys::IOEvents::Channel*, int, int, char const*) () from /usr/lib64/libXrdUtils.so.2
:#14 0x00007f59d943f509 in XrdSys::IOEvents::PollE::Dispatch(XrdSys::IOEvents::Channel*, unsigned int) () from /usr/lib64/libXrdUtils.so.2
:#15 0x00007f59d943f793 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /usr/lib64/libXrdUtils.so.2
:#16 0x00007f59d943df8d in XrdSys::IOEvents::BootStrap::Start(void*) () from /usr/lib64/libXrdUtils.so.2
:#17 0x00007f59d943b49f in XrdSysThread_Xeq () from /usr/lib64/libXrdUtils.so.2
:#18 0x00007f59d91faaa1 in start_thread () from /lib64/libpthread.so.0
:#19 0x00007f59d7211bcd in clone () from /lib64/libc.so.6
```
Backtrace appears to be "pure" xrootd-level?
```
~$ rpm -q xrootd-libs eos-fuse-core
1:xrootd-libs-4.8.1-1.el6.x86_64
1:xrootd-libs-4.8.1-1.el6.i686
(none):eos-fuse-core-4.2.4-2.el6.x86_64
```
We have a coredump (which might contain sensitive data, not uploading here).

**Comment by xrootd-dev** [comment]
Hi Jan,

Could you post this to github bug report issues along with what version 
this corresponds to.

Andy

**Comment by jmuf** [comment]
(backtrace is slightly different from #681, so posting here)
Saw another one of these (aaain from inside EOS code, but the backtrace is in the xrootd library):
```
:Core was generated by `/usr//bin/eosd /eos/atlas -obig_writes,max_readahead=131072,max_write=4194304,f'.
:Program terminated with signal 11, Segmentation fault.
:#0  0x00007fd7c4fec704 in XrdOucHash<XrdSutCacheEntry>::Find(char const*, long*) () from /usr/lib64/libXrdSecgsi-4.so
:#0  0x00007fd7c4fec704 in XrdOucHash<XrdSutCacheEntry>::Find(char const*, long*) () from /usr/lib64/libXrdSecgsi-4.so
:#1  0x00007fd7c4fdf3cc in XrdSecProtocolgsi::GetCA(char const*, XrdCryptoFactory*, gsiHSVars*) () from /usr/lib64/libXrdSecgsi-4.so
:#2  0x00007fd7c4fe032b in XrdSecProtocolgsi::ParseCAlist(XrdOucString) () from /usr/lib64/libXrdSecgsi-4.so
:#3  0x00007fd7c4fe7ffa in XrdSecProtocolgsi::ClientDoInit(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&) () from /usr/lib64/libXrdSecgsi-4.so
:#4  0x00007fd7c4fe855d in XrdSecProtocolgsi::ParseClientInput(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&) () from /usr/lib64/libXrdSecgsi-4.so
:#5  0x00007fd7c4fe892e in XrdSecProtocolgsi::getCredentials(XrdSecBuffer*, XrdOucErrInfo*) () from /usr/lib64/libXrdSecgsi-4.so
:#6  0x00007fd7da988c31 in XrdCl::XRootDTransport::GetCredentials(XrdSecBuffer*&, XrdCl::HandShakeData*, XrdCl::XRootDChannelInfo*) () from /usr/lib64/libXrdCl.so.2
:#7  0x00007fd7da9897e9 in XrdCl::XRootDTransport::DoAuthentication(XrdCl::HandShakeData*, XrdCl::XRootDChannelInfo*) () from /usr/lib64/libXrdCl.so.2
:#8  0x00007fd7da98a176 in XrdCl::XRootDTransport::HandShakeMain(XrdCl::HandShakeData*, XrdCl::AnyObject&) () from /usr/lib64/libXrdCl.so.2
:#9  0x00007fd7da98a343 in XrdCl::XRootDTransport::HandShake(XrdCl::HandShakeData*, XrdCl::AnyObject&) () from /usr/lib64/libXrdCl.so.2
:#10 0x00007fd7da9d129b in XrdCl::AsyncSocketHandler::OnReadWhileHandshaking() () from /usr/lib64/libXrdCl.so.2
:#11 0x00007fd7da9d1618 in XrdCl::AsyncSocketHandler::Event(unsigned char, XrdCl::Socket*) () from /usr/lib64/libXrdCl.so.2
:#12 0x00007fd7da97c143 in ?? () from /usr/lib64/libXrdCl.so.2
:#13 0x00007fd7da6cabb8 in XrdSys::IOEvents::Poller::CbkXeq(XrdSys::IOEvents::Channel*, int, int, char const*) () from /usr/lib64/libXrdUtils.so.2
:#14 0x00007fd7da6cad89 in XrdSys::IOEvents::PollE::Dispatch(XrdSys::IOEvents::Channel*, unsigned int) () from /usr/lib64/libXrdUtils.so.2
:#15 0x00007fd7da6cb013 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /usr/lib64/libXrdUtils.so.2
:#16 0x00007fd7da6c97cd in XrdSys::IOEvents::BootStrap::Start(void*) () from /usr/lib64/libXrdUtils.so.2
:#17 0x00007fd7da6c6a6f in XrdSysThread_Xeq () from /usr/lib64/libXrdUtils.so.2
:#18 0x00007fd7da485aa1 in start_thread () from /lib64/libpthread.so.0
:#19 0x00007fd7d7e00bcd in clone () from /lib64/libc.so.6
```
Version:
```
~$ rpm -qf /usr/lib64/libXrdSecgsi-4.so /usr/bin/eosd
1:xrootd-libs-4.8.3-1.el6.x86_64
(none):eos-fuse-core-4.2.22-1.el6.x86_64
~$ hostname
lxplus040.cern.ch
```
GDB (machine does not have full debuginfo, but looks like a NULL pointer being dereferenced?):
```
(gdb) f 0
#0  0x00007fd7c4fec704 in XrdOucHash<XrdSutCacheEntry>::Find(char const*, long*) () from /usr/lib64/libXrdSecgsi-4.so
(gdb) x/i $rip
=> 0x7fd7c4fec704 <_ZN10XrdOucHashI16XrdSutCacheEntryE4FindEPKcPl+52>:	mov    (%rax,%rdx,8),%r13
(gdb) print $rax
$1 = 0
(gdb) print $rdx
$2 = 126
(gdb) print $r13
$3 = 140564704194912
(gdb) x/x $r13
0x7fd7c542f160:	0x00000001
```

**Comment by abh3** [comment]
Hi Jan,

Ah, what release is this? There were some fixes in SI, Michal would know 
which release they made it to.

Andy

**Comment by simonmichal** [comment]
This haven't been fixed.

**Comment by gganis** [comment]
I'll take care of this on Monday. I think I know what the problem is.

**Comment by abh3** [comment]
Hi Jan,

I know this is going to be irksome, but could you install the debug RPM so that we can get some statement numbers in the backtrace? It’s near impossible to setup a context on which this occurs without statement numbers. Thanks.

Andy

P.S. If you still have the core file, just install the debug rpm and rerun the back trace.

**Comment by jmuf** [comment]
OK, here we go - hope this helps..
```
(gdb) bt
#0  0x00007fd7c4fec704 in XrdOucHash<XrdSutCacheEntry>::Find (this=0x7fd7c51f5a90, KeyVal=0x7fd7c54b1b60 "5168735f.0:1", KeyTime=0x0) at /usr/src/debug/xrootd-4.8.3/src/XrdOuc/XrdOucHash.icc:173
#1  0x00007fd7c4fdf3cc in Get (cahash=0x7fd7c54320f0 "5168735f.0", cf=0x7fd7c47ff640, hs=0x7fd7c542f160) at /usr/src/debug/xrootd-4.8.3/src/XrdSut/XrdSutCache.hh:97
#2  XrdSecProtocolgsi::GetCA (cahash=0x7fd7c54320f0 "5168735f.0", cf=0x7fd7c47ff640, hs=0x7fd7c542f160) at /usr/src/debug/xrootd-4.8.3/src/XrdSecgsi/XrdSecProtocolgsi.cc:4264
#3  0x00007fd7c4fe032b in XrdSecProtocolgsi::ParseCAlist (this=0x7fd7c5447500, calist=...) at /usr/src/debug/xrootd-4.8.3/src/XrdSecgsi/XrdSecProtocolgsi.cc:4530
#4  0x00007fd7c4fe7ffa in XrdSecProtocolgsi::ClientDoInit (this=0x7fd7c5447500, br=<value optimized out>, bm=<value optimized out>, emsg=...) at /usr/src/debug/xrootd-4.8.3/src/XrdSecgsi/XrdSecProtocolgsi.cc:2896
#5  0x00007fd7c4fe855d in XrdSecProtocolgsi::ParseClientInput (this=<value optimized out>, br=0x7fd7c54351d0, bm=0x7fd7d13fd8d0, cmsg=...) at /usr/src/debug/xrootd-4.8.3/src/XrdSecgsi/XrdSecProtocolgsi.cc:2807
#6  0x00007fd7c4fe892e in XrdSecProtocolgsi::getCredentials (this=0x7fd7c5447500, parm=<value optimized out>, ei=0x7fd7d13fd970) at /usr/src/debug/xrootd-4.8.3/src/XrdSecgsi/XrdSecProtocolgsi.cc:1379
#7  0x00007fd7da988c31 in XrdCl::XRootDTransport::GetCredentials (this=<value optimized out>, credentials=@0x7fd7d13fe230, hsData=0x7fd7d38693d0, info=0x7fd7d386a3c0) at /usr/src/debug/xrootd-4.8.3/src/XrdCl/XrdClXRootDTransport.cc:1879
#8  0x00007fd7da9897e9 in XrdCl::XRootDTransport::DoAuthentication (this=0x7fd7d384c5e0, hsData=0x7fd7d38693d0, info=0x7fd7d386a3c0) at /usr/src/debug/xrootd-4.8.3/src/XrdCl/XrdClXRootDTransport.cc:1650
#9  0x00007fd7da98a176 in XrdCl::XRootDTransport::HandShakeMain (this=0x7fd7d384c5e0, handShakeData=0x7fd7d38693d0, channelData=<value optimized out>) at /usr/src/debug/xrootd-4.8.3/src/XrdCl/XrdClXRootDTransport.cc:417
#10 0x00007fd7da98a343 in XrdCl::XRootDTransport::HandShake (this=0x7fd7d384c5e0, handShakeData=0x7fd7d38693d0, channelData=...) at /usr/src/debug/xrootd-4.8.3/src/XrdCl/XrdClXRootDTransport.cc:326
#11 0x00007fd7da9d129b in XrdCl::AsyncSocketHandler::OnReadWhileHandshaking (this=0x7fd7d386a280) at /usr/src/debug/xrootd-4.8.3/src/XrdCl/XrdClAsyncSocketHandler.cc:779
#12 0x00007fd7da9d1618 in XrdCl::AsyncSocketHandler::Event (this=0x7fd7d386a280, type=1 '\001') at /usr/src/debug/xrootd-4.8.3/src/XrdCl/XrdClAsyncSocketHandler.cc:234
#13 0x00007fd7da97c143 in (anonymous namespace)::SocketCallBack::Event (this=0x7fd7d384c560, chP=<value optimized out>, cbArg=<value optimized out>, evFlags=<value optimized out>) at /usr/src/debug/xrootd-4.8.3/src/XrdCl/XrdClPollerBuiltIn.cc:82
#14 0x00007fd7da6cabb8 in XrdSys::IOEvents::Poller::CbkXeq (this=0x7fd7d3bed1e0, cP=0x7fd7d3839200, events=1, eNum=0, eTxt=0x0) at /usr/src/debug/xrootd-4.8.3/src/XrdSys/XrdSysIOEvents.cc:693
#15 0x00007fd7da6cad89 in XrdSys::IOEvents::PollE::Dispatch (this=0x7fd7d3bed1e0, cP=0x7fd7d3839200, pollEv=<value optimized out>) at /usr/src/debug/xrootd-4.8.3/src/XrdSys/XrdSysIOEventsPollE.icc:270
#16 0x00007fd7da6cb013 in XrdSys::IOEvents::PollE::Begin (this=0x7fd7d3bed1e0, syncsem=<value optimized out>, retcode=<value optimized out>, eTxt=<value optimized out>) at /usr/src/debug/xrootd-4.8.3/src/XrdSys/XrdSysIOEventsPollE.icc:225
#17 0x00007fd7da6c97cd in XrdSys::IOEvents::BootStrap::Start (parg=0x7fff7aae6600) at /usr/src/debug/xrootd-4.8.3/src/XrdSys/XrdSysIOEvents.cc:131
#18 0x00007fd7da6c6a6f in XrdSysThread_Xeq (myargs=0x7fd7d384c7e0) at /usr/src/debug/xrootd-4.8.3/src/XrdSys/XrdSysPthread.cc:86
#19 0x00007fd7da485aa1 in start_thread () from /lib64/libpthread.so.0
#20 0x00007fd7d7e00bcd in clone () from /lib64/libc.so.6
#0  0x00007fd7c4fec704 in XrdOucHash<XrdSutCacheEntry>::Find (this=0x7fd7c51f5a90, KeyVal=0x7fd7c54b1b60 "5168735f.0:1", KeyTime=0x0) at /usr/src/debug/xrootd-4.8.3/src/XrdOuc/XrdOucHash.icc:173
173	   if ((hip = hashtable[kent]))
(gdb) info locals
khash = 6273236213436711438
kent = 126
hip = <value optimized out>
lifetime = 0
phip = <value optimized out>
(gdb) print hashtable[kent]
Cannot access memory at address 0x3f0
(gdb) print hashtable
$1 = (XrdOucHash_Item<XrdSutCacheEntry> **) 0x0
(gdb) up
#1  0x00007fd7c4fdf3cc in Get (cahash=0x7fd7c54320f0 "5168735f.0", cf=0x7fd7c47ff640, hs=0x7fd7c542f160) at /usr/src/debug/xrootd-4.8.3/src/XrdSut/XrdSutCache.hh:97
97	      if (!(cent = table.Find(tag))) {
(gdb) print table
$2 = {hashtable = 0x0, prevtablesize = 89, hashtablesize = 144, hashnum = 0, hashmax = 115, hashload = 80}
(gdb) up
#2  XrdSecProtocolgsi::GetCA (cahash=0x7fd7c54320f0 "5168735f.0", cf=0x7fd7c47ff640, hs=0x7fd7c542f160) at /usr/src/debug/xrootd-4.8.3/src/XrdSecgsi/XrdSecProtocolgsi.cc:4264
4264	   XrdSutCacheEntry *cent = cacheCA.Get(tag.c_str(), rdlock, GetCACheck, (void *) &arg);
(gdb) print tag
$3 = {_vptr.XrdOucString = 0x749050, str = 0x7fd7c54b1b60 "5168735f.0:1", len = 12, siz = 21, static blksize = -1}
(gdb) print arg
$4 = {arg1 = 1, arg2 = 86400, arg3 = 1527719441, arg4 = -1}
(gdb) up
#3  0x00007fd7c4fe032b in XrdSecProtocolgsi::ParseCAlist (this=0x7fd7c5447500, calist=...) at /usr/src/debug/xrootd-4.8.3/src/XrdSecgsi/XrdSecProtocolgsi.cc:4530
4530	            if (GetCA(cahash.c_str(), sessionCF, hs) == 0)
(gdb) print cahash
$5 = {_vptr.XrdOucString = 0x749050, str = 0x7fd7c54320f0 "5168735f.0", len = 10, siz = 11, static blksize = -1}
```
This CA cert file has apparently /not/ been changed around the time of the crash:
```
~$ locate 5168735f.0 | xargs ls -l
lrwxrwxrwx. 1 root root   15 May 22 09:23 /etc/grid-security/certificates/5168735f.0 -> CERN-GridCA.pem
-r--r--r--. 1 root root 3341 May 17 08:02 /etc/openldap/cacerts/5168735f.0
-r--r--r--. 1 root root 3341 May 17 08:02 /etc/pki/tls/certs/5168735f.0
~$ ls -l /etc/grid-security/certificates/CERN-GridCA.pem
-rw-r--r--. 1 root root 3341 May  4 19:26 /etc/grid-security/certificates/CERN-GridCA.pem
```

**Comment by abh3** [comment]
This is non-reproducible and seems to not have recirred for over a year.
