### ISSUE TITLE
Segfaults when cleaning up SSL session

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#820]
Just saw a corefile with this stack trace:
```
#12 <signal handler called>
#13 0x00007f17111d452c in free () from /usr/lib64/libjemalloc.so.1
#14 0x00007f170bc3860d in CRYPTO_free () from /lib64/libcrypto.so.10
#15 0x00007f170bd1512c in ASN1_template_free () from /lib64/libcrypto.so.10
#16 0x00007f170bd150a5 in ASN1_item_free () from /lib64/libcrypto.so.10
#17 0x00007f170bd10b7b in x509_cb () from /lib64/libcrypto.so.10
#18 0x00007f170bd14eca in asn1_item_combine_free () from /lib64/libcrypto.so.10
#19 0x00007f170bd150a5 in ASN1_item_free () from /lib64/libcrypto.so.10
#20 0x00007f170bceeaf0 in sk_pop_free () from /lib64/libcrypto.so.10
#21 0x00007f170c072a25 in ssl_sess_cert_free () from /lib64/libssl.so.10
#22 0x00007f170c073d37 in SSL_SESSION_free () from /lib64/libssl.so.10
#23 0x00007f170c070d1d in SSL_free () from /lib64/libssl.so.10
#24 0x00007f170c4c2c4e in XrdHttpProtocol::Cleanup (this=this@entry=0x7f16ec00f600) at /usr/src/debug/xrootd/xrootd/src/XrdHttp/XrdHttpProtocol.cc:1770
#25 0x00007f170c4c2fbe in XrdHttpProtocol::Recycle (this=0x7f16ec00f600, lp=<optimized out>, csec=<optimized out>, reason=<optimized out>)
    at /usr/src/debug/xrootd/xrootd/src/XrdHttp/XrdHttpProtocol.cc:952
#26 0x00007f1710f4b279 in XrdXrootdTransit::Recycle (this=0x7f16f2d28000, lp=0x7f16ef822028, consec=0, reason=0x7f16ec15b080 "send failure")
    at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdTransit.cc:475
#27 0x00007f1710ccdbc7 in XrdLink::Close (this=0x7f16ef822028, defer=<optimized out>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdLink.cc:385
#28 0x00007f1710cd11cf in XrdScheduler::Run (this=0x610e78 <XrdMain::Config+440>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:357
```
Source of the problem isn't clear currently -- looks like it's something to do with recycling of the protocol object?

**Comment by bbockelm** [comment]
(note - just putting this and #821 as a placeholder ... still debugging to verify it is actually an xrootd problem)

**Comment by bbockelm** [comment]
Closing this.  I think there was a different library stomping over OpenSSL's memory.
