### ISSUE TITLE
Segfaults when handling server certificate requests?

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#821]
Another segfault noticed when putting `master` under heavy load.  Seems to be due to some of the new GSI code?
```
#6  <signal handler called>
#7  XrdSecProtocolgsi::ServerDoCertreq (this=0x7f8f55d75140, br=0x7f8f55d191d0, bm=0x7f8f569fbfe0, cmsg=...) at /usr/src/debug/xrootd/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:3398
#8  0x00007f8f8f943905 in XrdSecProtocolgsi::ParseServerInput (this=this@entry=0x7f8f55d75140, br=br@entry=0x7f8f55d191d0, bm=bm@entry=0x7f8f569fbfe0, cmsg=...)
    at /usr/src/debug/xrootd/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:3310
#9  0x00007f8f8f943cca in XrdSecProtocolgsi::Authenticate (this=0x7f8f55d75140, cred=<optimized out>, parms=0x7f8f569fc468, ei=0x7f8f569fc490)
    at /usr/src/debug/xrootd/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:1705
#10 0x00007f8f95ee28e5 in XrdXrootdProtocol::do_Auth (this=0x7f8f55d7b280) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdXeq.cc:212
#11 0x00007f8f95c5ce19 in XrdLink::DoIt (this=0x7f8f5c0222d8) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdLink.cc:441
```

**Comment by bbockelm** [comment]
Closing this.  I think there was a different library stomping over OpenSSL's memory.
